### ISSUE TITLE
initial information architecture and nav

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#10]
"I'm a citizen seeing this on twitter and I want to know what the site is about before I lose ttention"

"I'm a citizen with a possible stash of PPE and just want to know what to do next"

"I'm a healthcare provider/organizer and need to update info"

**Comment by awong-dev** [comment]
Either code or wireframes would be useful.

**Comment by r-pop** [comment]
I'm not too stressed about CTA below the fold - above the fold is pretty compelling image rich content. Right now it's in the order of an argument (problem, evidence, call to action, what to find, where to take it).

One possibility, move the "We need to help the helpers, right now. We need to find the masks." above the embedded tweets. But I think this would be less compelling. Maybe they could be along side? But that wouldn't work for mobile. Hmm.

**Comment by awong-dev** [comment]
obsolete.
