### ISSUE TITLE
Add country partial for Spain About Us page

### ISSUE THREAD

**Issue by lizhaoqi99** [findthemasks/findthemasks#1019]
Their own dedicated About Us page using the regional_spotlight.handlebars logic. Updated Content for Spain team's Regional Spotlight: https://docs.google.com/document/d/1b9lj2j3vqJrZgqfozbZ2reSO6xnC_a00VtKO-xxUB7g/edit#bookmark=id.y85wopucp2ps

**Comment by ngottlieb** [comment]
resolved by #1032
