### ISSUE TITLE
Divert large inventory donations to a more appropriate resource

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#102]
Coordinating with other projects, we will need to add a pointer from our site to one that is equipped to do logistics + possibly compensation for the transfer of large inventory.

**Comment by saikatbhadra** [comment]
Can we close this @r-pop ? We are linking to getusppe.org/give which has a form for large donors.

**Comment by saikatbhadra** [comment]
Closing this as I believe this is addressed through getusppe.org links
