### ISSUE TITLE
Language drop-down options in their respective language

### ISSUE THREAD

**Issue by NickB64** [findthemasks/findthemasks#1023]
Instead of having each language on the dropdown menu be in whatever language the website is currently in, I'm thinking it might be a good idea to have these options in their own language (e.g., when the site is currently set to "English", the language option for French could be "français" instead of "French", and similarly for the other languages). This could help site visitors who don't know English and developers testing code in different languages.

**Comment by nburt** [comment]
Closed by https://github.com/findthemasks/findthemasks/pull/1047
