### ISSUE TITLE
fix title tag for findthemakers

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#1029]
Currently findthemakers.com renders a title tag of #findthemasks. This should be updated to #findthemakers

**Comment by eikhunter** [comment]
https://github.com/findthemasks/findthemasks/blob/master/views/layouts/main.handlebars#L11 - Looks like this has been done already and it updates accordingly on the live site

**Comment by ngottlieb** [comment]
resolved by #1043
