### ISSUE TITLE
Reevaluate Font Size Responsiveness, especially in an Embed context. 

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#1049]
This is part of OSMS's requests for making the map more embed friendly for makers.

![find-the-masks-embed-requests](https://user-images.githubusercontent.com/144579/84589404-1a617f00-ade3-11ea-8cca-64cdee51a90b.jpg)

**Comment by eikhunter** [comment]
https://github.com/findthemasks/findthemasks/pull/1064

**Comment by awong-dev** [comment]
@eikhunter is this completed by #1064? Can I close?

**Comment by eikhunter** [comment]
Yes it is, I'll close it for you
