### ISSUE TITLE
Allow for Toggle Button to show/hide list in embed

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#1051]
Add a way to hide the list easier. Ideally default collapse mode is also settable via a query parameter.

![find-the-masks-embed-requests](https://user-images.githubusercontent.com/144579/84589517-d58a1800-ade3-11ea-86d5-ac35dc64e185.jpg)

**Comment by tobiasdeml** [comment]
This would be a huge help to increase real estate of embeds on default loads. :-)

**Comment by eikhunter** [comment]
I'll take a look at this today

**Comment by eikhunter** [comment]
https://findthemasks-1051-list--e5gz8j.herokuapp.com/give.html
https://github.com/findthemasks/findthemasks/pull/1063

**Comment by tobiasdeml** [comment]
Yeah that's an excellent solution! Would be totally on board with something
like that (maybe a bit streamlined in style) bring pushed through!

Toby

--

Tobias Deml
+1 310.350.5384

Co-Founder & Producer/DP
www.prodigium.pictures
1601 Vine Street, Hollywood, 90028 CA

Co-Founder & Editor in Chief
www.cinemaofchange.com

**Comment by nburt** [comment]
closed by https://github.com/findthemasks/findthemasks/pull/1063
