### ISSUE TITLE
Polishing issue for email easy-buttons

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#1072]
Basic functionality for the easy-button links appears to work well! There are a few small changes that will make it even better.

1. LGTM-link should:
- Mark "Reason" for row-being-updated as "DU" 
- Mark "Mod-Status" for newly-updated row as "E"

2: Both LGTM and Removal links presently only return "success!" to the user who has clicked the link.

More-friendly/interpretable responses would be:

LGTM: "Your entry has been updated -- the updated timestamp will appear shortly. If it has not been updated within 24 hr, please contact data@findthemasks.com ."

Removal: "Your removal request has been received and the entry will be removed from our public registry shortly. If the entry has not been removed within 24 hr, please contact data@findthemasks.com"

N.B. The removal-link behavior is slightly different from our existing workflow, which would replicate a row at the leading edge marked "R", in addition to marking the removed row "R", but the timestamp is sufficient for history-reconstruction and rows may soon be at a premium. So, the existing behavior is okay.

**Comment by awong-dev** [comment]
done. I think. Should be live in like 10 mins.
