### ISSUE TITLE
Easy-button updates don't update entry_age, which blocks filters from picking up new entries

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#1076]
When the easy-button email updates copy new rows to the Sheet bottom, the entry_age cells copy the value, but probably not the formula.  Because of this, the entry_age number is not updated. The sheet-date filters use entry_age to determine which entries are highlighted.

Short-term workaround: the entry_age can be easily updated by hand. This approach works, but prevents easy-button submissions from going live quickly.

Possible solutions:

- configure the sheet to periodically-update the entry_age cells based upon the timestamps

- configure filters to use the timestamps instead of the entry age

The latter may be more resilient, the former may be more-readily implemented, as timestamps can be tricky to parse.

**Comment by zhuochenwang** [comment]
I'm gonna start and see if I can get the entry_age filter to work with timestamps instead of entry_age property!

**Comment by 4kbt** [comment]
Are we running on timestamps now? Can this bug be closed?

**Comment by cchang-adi** [comment]
Sorry for duplicate bug! https://github.com/findthemasks/findthemasks/issues/1093 If this issue gets closed, please feel free to close 1093 too.

**Comment by zhuochenwang** [comment]
Yeah, we are now using timestamp for the entry_age filter! It was merged with #1077!
