### ISSUE TITLE
(important for makers) Date filter doesn't work on embeds

### ISSUE THREAD

**Issue by tobiasdeml** [findthemasks/findthemasks#1079]
We beta-tested the tool on our embedded site if a maker can go from "hello, I want to check who's around me, and then what kind of demand is around me!" - if they activate the requester data, and then filter by last date added "1-7 days" the list is blank.
https://opensourcemedicalsupplies.org/local-response/

Very important to actually make the embed map workable.

Thank you!

**Comment by zhuochenwang** [comment]
Hey @tobiasdeml, sorry for the rather late reply. I'm currently working on a fix for this! The entry age is the first filter that can be applied to both requester and maker data so a little bit more coding is required. Will keep you updated on this!

**Comment by tobiasdeml** [comment]
Much appreciated :)
--
*Tobias Deml*
+1 (310) 350-5384

*Co-Founder/DoP&Producer      **Co-Founder/ Editor*
    [image: Cinema of Change]
www.prodigium-pictures.com
www.cinemaofchange.com
*Social Impact Entertainment       *
*Exploring the Influence of Films*
Instagram <https://www.instagram.com/prodigiumpics/> |  Facebook
<https://www.facebook.com/prodigium.pictures/> | Sample Work
<https://www.youtube.com/playlist?list=PLqqH12KmNoZQNFN4dorjcMp6icjI8zRhf>
 | Brochure
<https://www.dropbox.com/s/ghvrwsf5lplcyhv/PRODIGIUM%20PICTURES-2019.pdf?dl=0>

**Comment by zhuochenwang** [comment]
I think this issue is fixed through #1088. Could you check the functionality when you have the time? Thanks!

**Comment by tobiasdeml** [comment]
Yes, works! Thank you! :)
--
*Tobias Deml*
+1 (310) 350-5384

*Co-Founder/DoP&Producer      **Co-Founder/ Editor*
    [image: Cinema of Change]
www.prodigium-pictures.com
www.cinemaofchange.com
*Social Impact Entertainment       *
*Exploring the Influence of Films*
Instagram <https://www.instagram.com/prodigiumpics/> |  Facebook
<https://www.facebook.com/prodigium.pictures/> | Sample Work
<https://www.youtube.com/playlist?list=PLqqH12KmNoZQNFN4dorjcMp6icjI8zRhf>
 | Brochure
<https://www.dropbox.com/s/ghvrwsf5lplcyhv/PRODIGIUM%20PICTURES-2019.pdf?dl=0>

**Comment by zhuochenwang** [comment]
Glad I could help!
