### ISSUE TITLE
site only mentions N95 masks but P95 is same or better

### ISSUE THREAD

**Issue by sp1d3rx** [findthemasks/findthemasks#11]
N95 means it captures 95% of particles, N means not for oil particulates. P95 means resistant to oil particulates, R95 means somewhat resistant to oil particulates, so P > R > N, if you have a P95, R95, or N95, those are needed, it's not just N.

**Comment by r-pop** [comment]
Yeah I see your point. I'm not sure all of these (eg a P100) would be practical in a medical setting, but I how about I update the "other needs" section to discuss {P,R,N} {95, 99, 100}? Need a simple and short way to communicate this.

**Comment by r-pop** [comment]
I have a question out to some doctors about this.

**Comment by spitznagel** [comment]
It appears that the masks listed above are approved by the CDC for coronavirus, as well as some registered under alternate certification programs:
https://www.cdc.gov/coronavirus/2019-ncov/hcp/respirators-strategy/crisis-alternate-strategies.html

Perhaps we can have our partners at GetUsPPE add this clarification to their "Give" page under N95?
https://getusppe.org/give

That would probably add the clarification desired without overly impacting the user experience.

**Comment by spitznagel** [comment]
Merged into #340
