### ISSUE TITLE
Feature request: search for donation sites by proximity to my zip

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#115]
I think this is a short hop from what @susanashlock already did, thoughts? requested by inter-team conference.

**Comment by patricknelson** [comment]
Current map (per #108): https://findthemasks.com/index-map.html

I would love to help work on this. I think it should:

1. Update map results
2. Update listing
3. Search field potentially w/ autocomplete capability, a la https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

Missing anything @r-pop

**Comment by patricknelson** [comment]
Spider food/search keywords:
radius proximity nearby search find close nearest

Other:
hospitals providers healthcare

**Comment by patricknelson** [comment]
I was thinking from a UI/UX perspective. See my screenshot hack below!

1. A text field where you can enter any arbitrary address can be added.
2. A button to submit  (right side)
3. A link to integrate the navigator.geolocation so it's not ONLY on page load

![2020-03-22_23-38-39](https://user-images.githubusercontent.com/4269377/77294441-87142400-6ca1-11ea-9038-0d77d2040d33.png)

**Comment by patricknelson** [comment]
p.s. Method for auto suggesting addresses while typing: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by saikatbhadra** [comment]
This issue should be closed, search by zip has been implemented
