### ISSUE TITLE
Feature request: add link to Google Maps directions for each dropoff location's address

### ISSUE THREAD

**Issue by susanashlock** [findthemasks/findthemasks#126]
Would require adding a link to:
https://www.google.com/maps/dir/?api=1&destination="<ADDRESS>"

(Origin of directions defaults to user's location if they have location-detection enabled; otherwise an empty field for them to fill in)

Could add link to addresses in:
- list of places
- InfoWindows on map

**Comment by saikatbhadra** [comment]
Good idea, will look at this tomorrow
