### ISSUE TITLE
States without an included hospital

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#131]
HI, AK, ND, SD, WY, SC, AR, DE, IN, WI

Only 10 to go before we can reach @r-pop's goal of breadth.  As new masks begin to flow toward urban hotspots, broad coverage will be increasingly essential.

**Comment by r-pop** [comment]
Suggestion on how to call hospitals:
1. make sure they're not already in our data by looking on findthemasks.com
2. Have our form pulled up and just enter the data straight in - that will also help provide a script. https://docs.google.com/forms/d/13-Hl2fW16zMy1zRuXJSlCouWsw7toTygDe1FjNfcnIg/edit
3. call, ask for charge nurse ("which one?" "ER")
4. ask if they accept PPE donations from members of the public, and if they say yes, ask what they need, and what the procedure is to dropoff safely and properly. 
5. enter address city state yourself, taking care to use the street address they said for donations which may be different than the hospital address

**Comment by 4kbt** [comment]
Up to 49 states!  AK is missing . Haven't grepped for the other. Almost to 51 (PR included)!

**Comment by spitznagel** [comment]
Congrats team! It looks like we now have all states listed. I am closing this issue out.
