### ISSUE TITLE
Add related resources section or subpage

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#14]
Have gotten many suggestions to post two related categories of resources:

How to donate masks if you are a business or institution with a large supply, this org can coordinate your donation to highest need within WA: https://www.suppliessaveliveswa.org/

Various grassroots efforts to sew masks. Our site should stay focused on finding certified PPE, but ok to link to these resources for the crafters.

**Comment by yauwong** [comment]
Here’s another you could add:  https://www.medicalsupplydrive.com/

Medical students organizing collections of PPE and also urging people to contact research labs to donate their equipment.

**Comment by r-pop** [comment]
https://www.donateppe.org/

**Comment by spitznagel** [comment]
Partnership with GetUsPPE appears to have addressed this recommendation. Is this issue now closed?

![image](https://user-images.githubusercontent.com/8340647/77851249-df10c600-718c-11ea-9187-f38df9bee2cb.png)

**Comment by saikatbhadra** [comment]
I am going to close this issue as I think this issue is addressed by the getusppe.org links now.
