### ISSUE TITLE
Add link to list of approved respirators

### ISSUE THREAD

**Issue by mdturner** [findthemasks/findthemasks#148]
The FDA has issued an emergency use authorization for certain non-medical respirators to be used in medical settings (see the 'Personal Protective Equipment' section at https://www.fda.gov/emergency-preparedness-and-response/mcm-legal-regulatory-and-policy-framework/emergency-use-authorization#2019-ncov).  The list of approved respirators is currently at https://www.fda.gov/media/135921/download.  It may be helpful to link to this list for people to check before making donations.

**Comment by spitznagel** [comment]
Related to:
#82
#11

**Comment by spitznagel** [comment]
Merged into #340
