### ISSUE TITLE
Feature request: bottom nav bar

### ISSUE THREAD

**Issue by ctavispost** [findthemasks/findthemasks#150]
Goal: communicate purpose and let people quickly find what they want

Bottom nav is easier to reach on mobile, which is our main source of traffic. It should increase 'conversions' without getting in the way of the content.

Examples:

![navBottWires](https://user-images.githubusercontent.com/39510844/77347939-da17c680-6cf5-11ea-950f-e10c4127802e.jpg)

**Comment by ctavispost** [comment]
Wireframes from https://www.figma.com/file/8yOxUOoKRZepq48or7MNGa/findthemasksNav?node-id=0%3A1

![Group 3](https://user-images.githubusercontent.com/39510844/77351762-75f80100-6cfb-11ea-808a-e73ae57f4dc7.png)
![Group 2](https://user-images.githubusercontent.com/39510844/77351767-785a5b00-6cfb-11ea-9aea-723860d5f04a.jpg)

**Comment by r-pop** [comment]
I don't think we should add more nav... it's still a simple site, and graeme is working on making the intro content smaller.

**Comment by awong-dev** [comment]
Honestly the lack of nav actually got in my way of usage today on the phone (I donated some masks I found!).  If this is easy, it's a nice-to-have as we have motivated users who will grit through scrolling.

Agreed though that it should be extremely basic and low visual weight.

**Comment by ctavispost** [comment]
Implementation isn't difficult. I've got it running on: https://ctavispost.github.io/findthemasks/public/index.html

It requires two custom CSS classes, IDs added to three tags, and a five item UL in a nav container.

As it stands, the page is a bit long, it doesn't have a clear declaration of purpose, and it isn't initially obvious what people should do other than read more. The near-top nav text doesn't help with this, but adds clutter and confusion. Nor is the page particularly easy to read right now.

I know it's a simple site and you seem resistant to the idea of more nav. What would make you feel comfortable with this? The change seems pretty braindead and I'm struggling to understand the pushback.

**Comment by saikatbhadra** [comment]
I will be closing this as we now have a bottom bar which is currently being used for i18n
