### ISSUE TITLE
Design: make masks images less prominent as we increase scope to all PPE

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#152]
I need help with this. Requests coming from PPElink and others who are sending institutional traffic our way. 

Feedback from Zahra/PPElink:
- appeal is fine, communicates urgency and is still accurate
- jump link to add/donate helps (added by r-pop, could be styled better)
- mask images overshadow need for other PPE, that section could be redesigned to be more inclusive

@cjimmy @graemer thoughts?

**Comment by ctavispost** [comment]
PPElink has a list I can work from to try to sketch up some quick icons. I might not illustrate all of them, but if we get a cross-section, that should be good, right? We could add the list in bullets, as well, if we wanted to.

- N95 respirators
- Surgical masks
- Protective glasses/goggles
- Nitrile gloves
- Head covers
- Face shields
- Disinfectant wipes

**Comment by ctavispost** [comment]
For example:
![Shape 29](https://user-images.githubusercontent.com/39510844/77380271-efade000-6d37-11ea-9146-a3ed4e185efd.png)
![Shape 32](https://user-images.githubusercontent.com/39510844/77380273-f0467680-6d37-11ea-9211-2febbc5c11e6.png)
![Shape 31](https://user-images.githubusercontent.com/39510844/77380274-f0467680-6d37-11ea-94e2-1f6f47dfd4d5.png)
![Shape 30](https://user-images.githubusercontent.com/39510844/77380275-f0467680-6d37-11ea-8387-870b0e4aa318.png)

**Comment by ctavispost** [comment]
Alternatively, we could switch one of the mask images for this free image from the CDC, and add a caption like, "Medical workers need protective equipment like gloves and scrubs."
![cdc-_N7I1JyPYJw-unsplash](https://user-images.githubusercontent.com/39510844/77380881-98a90a80-6d39-11ea-862d-98848b8fc67e.jpg)

**Comment by saikatbhadra** [comment]
I am going to close this since we have 3 equipment types now in the main imagery.
