### ISSUE TITLE
findthemasks.com branding still appears momentarily when loading https://getusppe.org/give/

### ISSUE THREAD

**Issue by liamrosen** [findthemasks/findthemasks#177]
Perhaps will be solved with the website cutover @r-pop?

https://i.imgur.com/6yiU4YL.png

Mozilla Firefox, latest version

**Comment by saikatbhadra** [comment]
@liamrosen I am closing this as I can't repro. please re-open if you still see the issue.

**Comment by liamrosen** [comment]
Yeah, it was fixed. Looks much better now!
