### ISSUE TITLE
deploy.sh can't be used for topic branches

### ISSUE THREAD

**Issue by drwestco** [findthemasks/findthemasks#191]
Want to be able to deploy and test topic branches. deploy.sh clobbers these with what's in master; have to comment out these lines or not use the script. 

```
# Update the git repository
git fetch
git reset --hard origin/master
git clean -f

**Comment by drwestco** [comment]
Related to large issue #185, creating a staging environment

**Comment by awong-dev** [comment]
Hmm... I think we can just do a git reset --hard origin/topic-branch for each one we want to push?

Though, I personally think we should only do origin/staging.

If we want to view topic branches live, we should set up heroku integration and spin up a PR app.

**Comment by awong-dev** [comment]
obsoleted via pr apps.
