### ISSUE TITLE
Deduplicate our dataset

### ISSUE THREAD

**Issue by csakoda** [findthemasks/findthemasks#193]
As discovered by our data moderators, we have duplication of records in our core dataset, and some tooling would be helpful in identifying and resolving them.

Initial thought from @awong-dev 
> Another thought on dups...we can add a magic-url that does some attempt at "dup detection". So you'd load that page, and it could just try to scan the whole dataset and apply some rules for matching. someone would have to describe what those rules are to a dev, but it is a nice little boxed project that could be coded up.

Does anyone have any initial ideas of what rules we want to apply?

**Comment by 4kbt** [comment]
I'm amazed that this bug is still alive. It's really, really dead :).
