### ISSUE TITLE
Don't display the full list of hospitals by default

### ISSUE THREAD

**Issue by raindrift** [findthemasks/findthemasks#195]
The complete hospital list isn't useful. It's just waaaay too long now (which is awesome, that there are so many). In some states (like DE), it's still short enough to be worthwhile when filtered by state, but in CA even the filtered list is way too long.

I think what makes more sense is to automatically filter the list to display what is shown on the map at its current zoom level. Adding a button to the filter selector for "Match map" is also an option, though since the whole "list matches map" paradigm is so common, I think that might be too much UX cruft.

Here's how to get the currently displayed points out of the map:

https://stackoverflow.com/questions/2906427/how-to-get-all-visible-markers-on-current-zoom-level

**Comment by graemer** [comment]
Hold off on this one for now. Let's figure out a solution for better sorting (by nearest to me), search, or filters before we start trimming the list.

**Comment by vdalal** [comment]
Filters based on "Use my Location", "City, State" & "Zip Code" work reasonably well IMHO.

* The Map View adjusts automatically to show donation sites even though they may be far away. 
-- I checked a few locations and even for (say) Montezuma, IA or St. Croix, IN the map view was zoomed out to show the nearby donation sites

Additional filter widgets for consideration:
* Move the State filter option to "State" pulldown next to the "Use my location" option. Even remove the State option as I am not sure how it helps the donor
* "Filter by Accepted Items" is the other important filter (other than City, State or Zip code) but is getting lost below the "State" filter
* "Use my Location" & State filters are are working at the same time. Should be mutually exclusive
* Couldnt find a way to uncheck the state after I clicked on one
* Add "Find Nearest Donation point" link next to the "Use my Location" link which will give the nearest locations based on distance IF "Address, City, State" or "Zip Code" was provided
- Additional actions can be provided there including "Address", "Get Directions" & Filter based on "Type of PPE accepted"
* Add a "Reset filters" link


Other considerations:
* Remove the full list of hospitals. Only show donation points based on the filters


Will think of the UI/UX a bit more. The single page works great at the moment

**Comment by saikatbhadra** [comment]
I am closing this issue as we have infinite scroll which seems to be working well and improving performance! 🚀
