### ISSUE TITLE
Filter the map by accepted items

### ISSUE THREAD

**Issue by raindrift** [findthemasks/findthemasks#197]
Right now the item selector filters the list, but the map remains unchanged. It would be handy if the map and the list were more integrated (see #195 for more on this)

**Comment by graemer** [comment]
Go ahead with this. We'd like the map and list components to reflect the same sites, dependent upon the filters that are set. This already works for the `state` query param, but it's a bit janky as when I change the filter from CA (what the query param set) to CO (via the UI), the map doesn't update.

**Comment by drwestco** [comment]
Multiple-state query is a special case of this. If the map and list/filter view was always in sync, this would be covered.

For single-state query: give.html?state=WA, the map view is set to the center+zoom of that state, and only pins for that state are shown. Filters and list match the map - only results from WA.

For multi-state query: give.html?state=WA,ID, the map view and pins represent the entire US. Filters and list correctly set to only show results for the two requested states.

**Comment by drwestco** [comment]
I'm going to tackle this one.

**Comment by drwestco** [comment]
Done.
