### ISSUE TITLE
After the dupe-detector runs, how many dupes remain?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#205]
In order to decide how much moderator effort to expend on de-duping, we need to know how many duplicates survive the Sheet-tab dupe detectors.

How many new entries are dupes after the dupe-detector is cleared? 1%? 5%?

What do those dupes look like?

**Comment by susanashlock** [comment]
To clarify what Charlie meant: he's asking how many 'actual' dupes remain after using our dupe-moderation flow.  This will tell us if we can/should improve our dupe-detection process.

This task involves playing around with data.

**Comment by 4kbt** [comment]
We've got dashboards. They're good (if broken right now). This bug is solved.
