### ISSUE TITLE
Script to convert link text to HTML

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#217]
When people enter links in our form, they show up as plaintext on index.html by default, not clickable links. 

Google Sheets is able to recognize link text and often creates links in the cells if that's the only text there (but it seems not to if there is other text around it, which is the case about 50% of the time). However this also doesn't translate to live links on the site.

For now, I am going through searching the sheet for "http" or "www" or even just ".edu" ".com" ".org" "bit.ly" and then manually adding the <a tags myself and testing the links.

Is there a way to automate this process?

**Comment by krithin** [comment]
I'm looking into doing this with https://www.npmjs.com/package/linkifyjs

**Comment by cchang-adi** [comment]
This seems to be working well, thanks everybody! :)
