### ISSUE TITLE
Bookkeeping in "approved" column?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#219]
Can we do book-keeping with the "approved column" of the "moderated" tab?

Per a discussion with @susanashlock , it sounds like the only thing done with the "approved" column is to check for the string "x".

At present, we do all of our inter-moderator communication about individual entries through Google Sheet comments on that cell. 

Sometimes those discussions are a short thread, but almost all of them are of the form "Dupe with 746"  or "Updated per 1145" or "Superseded by 832", or "Assimilated into 1235"

Can we overload that column with "Dupe746", "Updated1145", "Super832", "Assim1235", etc?

We promise to try not to use "x324". :).

**Comment by susanashlock** [comment]
Looked through code on GitHub and in our Apps Script.  Looks like we only look to check if the value is exactly equal to "x".

**Comment by awong-dev** [comment]
Yes.  You could infact to x65 if you want. If that's good enough, please close.

**Comment by awong-dev** [comment]
Actually, I'm closing. Reopen if needed.
