### ISSUE TITLE
Support for i18n ?country={us,fr,ch} query param

### ISSUE THREAD

**Issue by graemer** [findthemasks/findthemasks#222]
Add `?country={2 letter code}` param:

**Accomplished 2 things:**
Sets language to the specified language
Switches to country-specific json asset: us special-cases to data.json, the others will be data-fr.json, data-ch.json, etc.

**Comment by nburt** [comment]
I can pick this up. Do you know when data-fr.json and data-ch.json will be available for testing?

Also, do we want to gracefully handle invalid country codes or country codes that don't exist by falling back to US / data.json?

**Comment by nburt** [comment]
Also, do you know what the forms will look like? Wondering if existing filters (e.g. state) will continue to work or if we'll need to handle that differently.

**Comment by nburt** [comment]
opened a draft pr: https://github.com/r-pop/findthemasks/pull/226

**Comment by nburt** [comment]
Closing since this is deployed for French
