### ISSUE TITLE
Google Sheet Dupe-Detectors broken by Sheet re-org

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#224]
Fixing them is likely to be a few-character change. They need to point at Form Responses, and the columns have shifted. 

Dupe Addresses should point at Column F ("Final Address").

Dupe Names should point at Column E (what is the name of the hospital... )

**Comment by csakoda** [comment]
Where can I see the sheet?  I don't think I have access. @r-pop 

The dedupe is implemented as some AppScript?  Where can I see that?  What perms do I need to edit it? @cchang-adi

**Comment by r-pop** [comment]
It's here: https://docs.google.com/spreadsheets/d/1GwP7Ly6iaqgcms0T80QGCNW4y2gJ7tzVND2CktFqnXM/edit#gid=2027792507

Please request access from your google account and I will give view access.

**Comment by csakoda** [comment]
Thanks @r-pop I've requested from cms235@gmail

**Comment by csakoda** [comment]
I've added the following to the dupedata sheet

<img width="303" alt="image" src="https://user-images.githubusercontent.com/4173737/77704814-33dcf280-6f7b-11ea-98af-5923d4a9465d.png">

I now see addrs and names in the dupe addr/names sheets

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4173737/77704848-54a54800-6f7b-11ea-8bbc-4d7c68f5d209.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/4173737/77704854-5838cf00-6f7b-11ea-9cae-d5a10399438a.png">


@r-pop @awong-dev Please let me know if I have missed or broken something

**Comment by csakoda** [comment]
I made an additional edit to reflect the new positions of the City/State/Final Addr columns on both the Dupe Names and Dupe Addresses sheet.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/4173737/77705002-bf568380-6f7b-11ea-8a02-4ba1ee79b7db.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/4173737/77705075-f462d600-6f7b-11ea-86ae-e3bb672acb5c.png">


The headers make sense now :)

**Comment by csakoda** [comment]
@r-pop I don't have perms to assign + close this ticket, but I believe it has been validated and can be closed

<img width="841" alt="image" src="https://user-images.githubusercontent.com/4173737/77707584-c92fb500-6f82-11ea-8f6c-2dd4f3c2dcfa.png">

**Comment by cchang-adi** [comment]
Yes, closed! Thanks again!
