### ISSUE TITLE
Automation for expedited Update/Removal requests

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#225]
Data team needs to consult with Google Sheet wizards to develop sheet-tabs similar to the Dupe Detector tabs for update/removal requests.

Bonus points for #data Slack integration for new removal requests.

**Comment by susanashlock** [comment]
Another possible solution on top of 4kbt's: use a filter view in the existing tab that simply shows unprocessed update / removal requests.

**Comment by 4kbt** [comment]
The links on the dashboard to @susanashlock's filters are sufficient. Can reopen if someone feels really motivated.
