### ISSUE TITLE
Categorization Documentation needed

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#229]
In order to communicate better with those who consume our data, we need to document our categorization clearly.

This should be a separate wiki page from our Procedures page, to avoid confusion for our consumers. 

It should outline the categories that come from the from, how we do any category-correction, and extra categories/decorators we might add.

**Comment by cchang-adi** [comment]
As part of hand-categorizing all of CA now, I've decided that anything that has an ER is a hospital.

**Comment by JGLee6** [comment]
I guess working definition for myself was anything that had inpatient facilities, ie. beds.

**Comment by cchang-adi** [comment]
That too, inpatient is the definition I found while Googling.

**Comment by JGLee6** [comment]
Here's a start:
Hospital - A general or specialized institution providing medical or surgical treatment typically including inpatient facilities.

Outpatient clinic - Part of a hospital or independent clinic for the diagnosis or treatment of patients who do not require a bed. Including urgent care, pediatric, orthopedic, and diagnostic facilities.

Skilled Nursing Facility - a healthcare institution that has at least one full-time registered nurse (many facilities have much more than this on staff at any given time) as well as a doctor, provides nursing care 24 hours a day, and has a place to store and dispense medication. The staff at skilled nursing facilities also help with meals and personal hygiene. 

	Maybe the category should be changed to reflect inclusion of nursing homes/assisted living/hospice/home care since they may technically be different, but I have at least included in same group.

Doctor's Office - Individual practice, should maybe just be switched to outpatient as well

Ambulatory Surgical Center

Rehab Facility

Mental Health

Addiction Facility - Drug or alcohol rehabilitation and addiction treatment including inpatient rehab or outpatient treatment.

Pharmacy - A facility for preparing, compounding, and dispensing medicinal drugs.

Dentist - Facility for the practice of dentistry, orthodontics, and other oral health.

Emergency Medical Services - including ambulance services or paramedic services, are emergency services which treat illnesses and injuries that require an urgent medical response, providing out-of-hospital treatment and transport to definitive care

Public Health Facility

**Comment by JGLee6** [comment]
**Updated. Lacking good def for Public Health. Please review/edit**
Hospital - A general or specialized institution providing medical or surgical treatment typically including inpatient facilities.

Outpatient clinic - Part of a hospital or independent clinic for the diagnosis or treatment of patients who do not require a bed. Including urgent care, pediatric, orthopedic, and diagnostic facilities.

Skilled Nursing Facility - a healthcare institution that has at least one full-time registered nurse (many facilities have much more than this on staff at any given time) as well as a doctor, provides nursing care 24 hours a day, and has a place to store and dispense medication. The staff at skilled nursing facilities also help with meals and personal hygiene. 

	Maybe the category should be changed to reflect inclusion of nursing homes/assisted living/hospice/home care since they may technically be different, but I have at least included in same group.

Doctor's Office - Individual practice, should maybe just be switched to outpatient as well

Ambulatory Surgical Center - medical facilities that specialize in elective same-day or outpatient surgical procedures

Rehab Facility - Facilities devoted to the rehabilitation of patients with various neurological, musculo-skeletal, orthopedic and other medical conditions following stabilisation of their acute medical issues. Includes physical/occuptational therapy and transfer services.

Mental Health - Facilities specializing in mental and behavioral health including inpatient care or outpatient treatment

Addiction Facility - Drug or alcohol rehabilitation and addiction treatment including inpatient rehab or outpatient treatment.

Pharmacy - A facility for preparing, compounding, and dispensing medicinal drugs.

Dentist - Facility for the practice of dentistry, orthodontics, and other oral health.

Emergency Medical Services - including ambulance services or paramedic services, are emergency services which treat illnesses and injuries that require an urgent medical response, providing out-of-hospital treatment and transport to definitive care

Public Health Facility - ?????

**Comment by cchang-adi** [comment]
I've seen "Community Health Center" - synonymous with Public Health Facility? Was that the intent?

**Comment by cchang-adi** [comment]
I think we need a separate category for "Urgent Care" - this is more than just an outpatient clinic, since a lot of these are setting up COVID-19 testing and thus have higher needs for PPE than a typical clinic.

**Comment by r-pop** [comment]
Added "Urgent Care"

**Comment by 4kbt** [comment]
Done (or at least well-begun) -- see https://github.com/findthemasks/findthemasks/wiki/Categories
