### ISSUE TITLE
Category Addition

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#230]
We are going to need to add extra richness to our categories (see "categorize" in Data-procedures wiki, as of 3/26 10 am) in order to capture what we see in our data.

We can aggregate extra categories that we believe need addition to the Form in this Issue.

Dialysis Centers are a definite need.

**Comment by 4kbt** [comment]
Got an email requesting Home Health or Home Care. I think this came up on Slack, too.

We need an "Other", too.

**Comment by cchang-adi** [comment]
Also add: 

- Community Health Organization
- Diagnostic Lab
- Healthcare Union

**Comment by r-pop** [comment]
Added all these and "Other"
