### ISSUE TITLE
Alphabetize large city multiple hospital listings

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#231]
Large cities (ie Boston) have big lists of hospitals that are currently presented in somewhat haphazard order. Is there a way to alphabetize them under the city listing?

**Comment by drwestco** [comment]
Easy. On it.

**Comment by alex** [comment]
Done!

**Comment by cchang-adi** [comment]
Sorry to reopen this, alphabetization of entries within one city doesn't seem to be working anymore.
