### ISSUE TITLE
Text on intake to indicate delay in posting

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#234]
We see a lot of duplicate submissions that are often spaced out within a few minutes/hours of each other, which all didn't get posted because they were waiting for a mod to approve (eg. rows 1029, 1032, 1046, 1125). Lag in posting may also be (justifiably) distressing to submitters who don't see their facility come up immediately.

Can we add text to either main landing page or the top of the form to say something like "Your listing will be approved as soon as possible"? (UX pros please give feedback or opinions on optimal text?) Just to hint that there is a delay due to human intervention, and things don't go straight from form to display. May be reassuring to submitter as well.

Goal is to cut down on human deduping effort. In the particular case cited, we got a "fuzzy" dupe that evaded automated dedupe, and required me scanning the site visually state-by-state to catch. Eg 1029, 1032, and 1046 were caught in Dupe Names and Dupe Addresses from facility name match, but 1125 wasn't caught until manual review, due to abbreviated facility and city name.

**Comment by dhruv4** [comment]
I can jump on this and add some text to index.html and give.html. I don't think I can update the Google form.

**Comment by cchang-adi** [comment]
Thanks for the new text on the form! I think I've seen a drop in repeat submissions today already, so this is probably both comforting for the end users and much less mod work for us.
