### ISSUE TITLE
Snapshots/backups of Google Sheet

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#238]
We need regular snapshots of the Google Sheet (hourly?), in case something goes wrong.

Until then, post a comment here if you have recently made a snapshot.

You can copy the Sheet by using "File --> Make a Copy" . Rename it with a prefix like 1425 3/26.

Hand copies probably need not occur more often than every ~6 hr.

**Comment by 4kbt** [comment]
1426 3/26.

**Comment by susanashlock** [comment]
I just set up an Apps Script to backup every 2 hours to a Google Drive location currently shared with @4kbt and @r-pop .  If anyone else wants permissions, just let me know.

The script can be viewed by going to Tools > Script editor from the spreadsheet.
