### ISSUE TITLE
Resolve "email me" w/no address vs. user privacy promise dilemma?

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#245]
Problem: submitters are putting "Email me" in the instructions field, but then not providing an email address. 

This was just an impossible problem to solve when we didn't even collect emails before (ie line 760).

Now that we have email addresses that we are keeping private*, this gets complicated but potentially solvable. Submitters are still asking for prospective donors to email them in the instructions without giving their emails outside of the private field:
 
line 1922: "Please email the provided email or call XXX-XXX-XXXX"
line 1959: "Please contact us at our email and we will arrange curbside pickup of any donated goods"
line 2022: "Email me; will pick up in front of hospital at anyway anytime. Thank you!"

Since we've promised to keep the emails private, donors can't email them per the instructions! The donors could try to find out what the address is from us by emailing info@getusppe, but that is also not referenced on findthemasks.com.

Would something like the Craigslist mail relay be the right answer here, providing a temp forwarding address that protects submitters from spam at their real addresses, but allows for anyone who can see it to contact them? Is that possible to implement, or too much overhead to set up? 

Or should we tell donors to email us for the private address and handle it that way?

Any other suggestions?

*At the top of our form, we have this text: "Email addresses entered in the first field are private, but email addresses entered in "Drop off instructions" may become targets for spam." I take this as a promise to our end-users for privacy!

**Comment by 4kbt** [comment]
The Craigslist mail relay is a really thoughtful idea.  Anyone know a Craigslist dev?

First-draft could be accomplished with simple findthemasks mail forwarding cut-and-paste into our datastream?

No code needed, just an eager-beaver dev who likes editing mail-forwarding configuration files, and a willingness to comb through the data every six hours.

**Comment by cchang-adi** [comment]
Another possible solution is a little form popup where people can email to that address, but can't see what the address is. That prevents spam to hospital contact emails, while directly connecting donor to hospital contact. The emailto: links are sitting ducks for spammers.

**Comment by liamrosen** [comment]
How about an MVP solution where we just change the text to warn people leaving contact information here that the info will be public?

**Comment by r-pop** [comment]
@liamrosen you're describing the current state, which has led to the problem described in this issue - dropoff instructions that say "email me" with no email address.

I'll go change the form now so that the dropoff instructions say "if you need donors to email or call you, please include contact info that can be made public in this field"

**Comment by r-pop** [comment]
Implemented as:

"Drop off instructions, eg curbside procedure or mailing address. If you want donors to email or call you, please include contact info that can be made public in this field:"

The top of the form that collects email (required, for editing the form and future outreach) and phone (optional) says: "Information entered here will become public. Please type carefully and do not include personal phone numbers.
Email addresses and phone numbers entered in the first two fields are private, but email addresses entered in "Drop off instructions" may become targets for spam."

**Comment by r-pop** [comment]
re: craigslist mail relay, I will leave this up in case someone knows an easy way to set that up, but my first opinion is it increases the complexity significantly. I'd rather trust hospitals to define their procedures.

**Comment by cchang-adi** [comment]
What about a web form where the sender can't see the address it goes too? Is that harder/easier than mail relay?

**Comment by vdalal** [comment]
mailinator.com or another email forwarder/relay like craigslist, mailgun) with good API support:
1. Assign relay/forwarder email account (id) for every (say) hospital or every transaction (i.e. a new email id per donor <--> hospital pair)
- a random 6 character alphanumic string = 36 ^ 5= ~60 mil email ids
2. The actual hospital email address is added to that relay/forwarder email account via API. Thus, never public or visible to the donor
3. Forwarding set on the relay/forwarder email id via API e.g. relay email id --> actual hospital email id
4. Share the relay/forwarder email id with the donor
4a. If we go with the ONE email id/transaction, abuse vector is limited to that ONE donor
5. (enhancement) Remove forwarding/relay after TBD days (e.g. 3 days for donor to connect/drop off)
6. (enhancement) Recover email ids after (say) 2 weeks

Disclosure: Not affiliated with mailinator.com or any of the other companies cited above

PS:

mailinator charges $159/month for the plan that likely works for us.
Team Plus
$159 / Mo
Billed Annually
+  Unlimited Private Inboxes*
+  1 Private Domain
+  Up to 3 msgs/sec
+  API access to all email
+  2000 Email reads per day
That's ~60,000 per month!
+  50MB Storage
+  Use Rules to Route Messages
+  Web, API, or Webhook access
+  5 Team Accounts
+  Full statistics
+  Email Support

**Comment by r-pop** [comment]
@vdalal that all sounds great. Are you willing to set it up? I can pay (monthly) but what I actually want to do it reach out to them and see if they can comp us the Team Plus plan because we are a COVID response site acting in the public interest. Many services have policies like this right now.

**Comment by vdalal** [comment]
@r-pop I am attempting to do just that. Stay tuned.

**Comment by vdalal** [comment]
I am not hearing back from mailinator.com, no # to contact them either. I will find other options.
Note to self: Read the vendors privacy policy to be sure that there is no potential for abuse

**Comment by vdalal** [comment]
Team, we have the 2 week free trial setup with mailinator.com available now (my email id, but happy to share the details). Details below. API token is available too.

I am going to test it for our usecase. If it works, will request mailinator for a new account (based on findthemasks email id) for a longer trial (6 months) or reduced fee based on our mission.
If we had any stats of our donor <--> requestor transactions/day, will use that to build a more stronger case with them.


[snip]
Test Your Own Private Domain
You now have your own Private Domain! All email in that domain stays Private to you, sticks around until you delete it (or you fill up your storage), and doesn't have rate limits !

Your Private Domain is:   findthemaskscomteam.m8r.co
(You can change it on the Team Settings page)

All email sent to <any_inbox>@findthemaskscomteam.m8r.co will arrive in your Private Team Inbox.
You can try it right now! Send an email to:

test1@findthemaskscomteam.m8r.co

Then check your Private Team Inbox.Use the API to fetch messages
You also have access to all Mailinator email (public and private) through our API. You'll find your token on the Team Settings page. Use that token in a Authorization Header to authorize your api calls (see the API documentation for more information).
Want to see the API in action? Click the link below to see all email in the public test inbox.

You can of course use the API to read your Private Domain email too. Consult the API documentation for specifics!

Try it now - click this link to test the API:

https://api.mailinator.com/v2/domains/public/inboxes/test

(Note JSON is often not well-formatted in web browsers but you get the idea).

API token: AVAILABLE TOO

[snip]

**Comment by vdalal** [comment]
@r-pop  @raindrift 
I ran into a snag with mailinator - they dont forward emails!
Once email is received in the mailbox, they can web post to to a handler at findthemasks.com/mailHandler

I have created a slidedeck for our review: https://docs.google.com/presentation/d/1xdyGWwTAcZEPqx26hVxjPzgSPGZAqJaKRTYSY5BOceg/edit?usp=sharing

I need someone who can review the usecase, proposal before we start implementing it. Shall i work with Ian?

**Comment by vdalal** [comment]
Review the concept slides with @raindrift 
https://docs.google.com/presentation/d/1xdyGWwTAcZEPqx26hVxjPzgSPGZAqJaKRTYSY5BOceg/edit#slide=id.p

Ian's feedback:
* Use mailgun, he (we?) already have an account
* Best if emails go from findthemasks.com. Credibility/Reputation
-- we can make a subdomain like mail.findthemasks.com or something so that we don’t have to mess with the current email config
* Also, to get DKIM and SPF to work right, we’ll need to set some DNS records. Not doing it will hurt deliverability
* None of that should get in the way of developing the forwarder, since that can happen with any account. But we should get started with it soon since sometimes records can get cached, and then it takes time for them to be able to see the changes and verify the domain.

Challenge with mailgun (I will followup with them)
* Verified domains are not subject to a sending limit of 300 emails per day. ELSE, we are limited to 300 emails per day

**Comment by vdalal** [comment]
Hi team:

Per discussion with @raindrift, we believe that these are the next steps:
1. make sure there’s broad agreement from the project that this is the right thing to do

Can we get some consensus around this point?
Any other questions in anyone's mind?
Any other ideas that anyone has that we need to weigh?

@r-pop 

PS:

Once we have some consensus around point 1, the other steps are:
2. configure the domain (Ian can take care of this, as long as I can work with someone who has access to the dns)
3. build and deploy the forwarder app

**Comment by vdalal** [comment]
per discussion in slack #general from a few days back, agreed to go ahead with this. @raindrift completed the mail settings on mailgun and is working on the POST handler.
@raindrift, please let me know if I can be of any assistance.
Also, can I assign this bug to you?

**Comment by nburt** [comment]
added encrypted email field: https://github.com/findthemasks/findthemasks/pull/689

**Comment by ngottlieb** [comment]
Trying to determine actionable items in this issue. The encrypted email + contact form has solved some of this...but it seems like we're still facing the situation where users put their email address into the Instructions field -- so maybe we need to solve that?

We can parse it out and replace it with mock text and a notice suggesting they use the contact form...or replace it with a link to the contact form? But it's still in `data.json` -- so maybe better to attempt to solve it upstream at the form processing level?

@nburt (or @saikatbhadra or anyone else) -- am I right that's the only remaining step, and any thoughts on how to proceed with it?

**Comment by nburt** [comment]
I agree that filtering at the sheets level before things are exported to data.json is best. @cchang-adi @4kbt how are we handling email addresses in instructions now that we have a private field? Can we remove all emails from instructions and put them in the "_email" column if we aren't already?

**Comment by cchang-adi** [comment]
Yes, we can get the mods on this change. This is awesome!

We’ll also have to change the Google form instructions that say to leave an email.

**Comment by saikatbhadra** [comment]
Some ideas:
1. Form instructions - make sure all forms make it clear where to put your email and where not to
2. Form validations - If user puts their email in a form field that shouldn't have it, we should have form validation preventing a submission in this case (I don't know if google forms supports form validation, might have to wait for something like airtable)
3. Sheets validation -  Solve the problem downstream at the Google sheet. Search the relevant columns (using a regex or something) for email like text and warn the moderator in some column so they can fix it. We should also prevent these rows from being published ideally.

So I believe all the remaining TODOs need to happen upstream (form instructions, form validation, sheets validation) in the data flow rather than happening on the website @ngottlieb

**Comment by linderr** [comment]
I have time today to change all the Forms language site-wide after we decide how to deal with the Instructions field

**Comment by nburt** [comment]
Can we close this and move anything else to new issues?

**Comment by saikatbhadra** [comment]
I have created 3 issues for the follow up tasks, and will close this.
