### ISSUE TITLE
Remove 'moderated' tab from spreadsheet

### ISSUE THREAD

**Issue by susanashlock** [findthemasks/findthemasks#252]
Currently the moderated tab is a copy of the 'Form Responses 1' tab.  The copy is made by using the ARRAYFORMULA function.

I suspect that because it has to update every time a change is made in 'Form Responses 1' it's slowing down moderators.  I typically see the loading bar display when responses come in or moderators do work.

To make this happen, we'd need to point any scripts or code that points at the 'moderated' tab at the Form Responses 1 tab instead.  Known scripts that do this:

1.  Apps Script
2.  functions/index.js (the Firebase Cloud Functions).

I can easily take care of #1 but would need some help on #2.

**Comment by cchang-adi** [comment]
Closing since this is long since done already thanks to Susan and Albert and co.
