### ISSUE TITLE
Test spreadsheet moderation with 20k rows

### ISSUE THREAD

**Issue by susanashlock** [findthemasks/findthemasks#254]
What breaks if our spreadsheet grows by an order of magnitude (20k rows)?  

Does moderation slow down to a crawl?

Should test out:

- quick mod
- data-moderators
- update/removal moderators
- de-duplication moderators

**Comment by saikatbhadra** [comment]
@4kbt @susanashlock  - do you think this is still necessary? Given current load and a probable shift to airtable, I think we might want to close this

**Comment by 4kbt** [comment]
Go for it.
