### ISSUE TITLE
Tie up important loose-end from ye olde 12am March 26 Sheet-Refactor

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#257]
When refactoring the Google Sheet on the night of 3/25-26, we made the address-of-record the "Final Address" column.

The entries in that column were formerly Column ~"N",  and were auto-generated from API calls. 

Prior to the refactor, the addresses-of-record were those located in the "Street address for dropoffs" field. Those should be copied into to the Final Address Field for rows prior to the refactor.

This sounds trivial, but some rows, mostly moderated-off, would lose most meaning if the copy were performed as a bulk action.  @susanashlock  is probably the right person to make the copy, if not @4kbt.

**Comment by susanashlock** [comment]
This will involve rows 3-1822.

Will need to skim through and make sure all addresses look good before copying them into 'Final Address' column.

Would also be good to pause scripts before doing this, just in case.

**Comment by 4kbt** [comment]
At this point, we're never going to do this.
