### ISSUE TITLE
Should “Reset map” also clear text input and selected filters?

### ISSUE THREAD

**Issue by patricknelson** [findthemasks/findthemasks#264]
For usability purposes, might be easier to reset the search text field **and** selected state/equipment filters as well when user clicks “Reset map”. Minor oversight on my part not to bring up for discussion earlier, as that link was intended to return to initial page load state (post user geolocation). 

Opening issue for discussion!

**Link:** https://findthemasks.com/give.html?hide-search=false

**Comment by drwestco** [comment]
Clear text, definitely. 

In addition, It should either: 
a) reset the filters
b) reset the map to match the current filters

In the current UX, since the search+reset controls are separated from the filters by quite a bit, I'd vote for b).

**Comment by patricknelson** [comment]
I agree, any opinions @graemer or  @awong-dev ?

**Comment by patricknelson** [comment]
Forgot to note that I lean a little bit more toward "a" (resetting filters) insofar as it matches original filters on page load. So, if you start on `FL` it should reset map to that initial state.

**Comment by patricknelson** [comment]
Made a really quick PR for that here: #414 

Decided to pass on changing filters, partly due to not having access to initial state, but also because of separation of concerns. IMHO, resetting the map should do just that and the filters serve another [higher level] function.
