### ISSUE TITLE
Ascribing a unique ID to each entry

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#268]
At the moment, each entry in the Sheet is identified by row number. This is easy, but has downsides.

1. We cannot delete rows, whether we want to or not.
2. If anyone ever presses the "sort" button, on any column, including timestamp (thanks to form-updates) we lose all reference to our row-id system without reverting to a backup.

If it is a separate field, it could follow its way into the json and find a way to come back to us as an error code in emails. FTM-ID:3141

**Comment by cchang-adi** [comment]
Simplest solution may be just to turn present row numbers into another column that is an explicit index one?

**Comment by marcuscollins** [comment]
Timestamp + Facility Name is unique, so far, but agreed a primary key is needed.

**Comment by cchang-adi** [comment]
Timestamp actually gets updated if the form respondent also updates the entry using the link we send them in the email receipt. Thus, it's not guaranteed to stay stable.

**Comment by marcuscollins** [comment]
> Timestamp actually gets updated if the form respondent also updates the entry using the link we send them in the email receipt. Thus, it's not guaranteed to stay stable.

Then we definitely should prioritize a primary key.

**Comment by saikatbhadra** [comment]
can I close this @4kbt ? I can generate a UUID per row but I suspect this will slow down the sheet and I don't think anyone is sorting the sheet. I can build this into our airtable flow when we move to that

**Comment by 4kbt** [comment]
Yes --- the "source row" in the current sheet almost achieves this goal.
