### ISSUE TITLE
Clickable link to aid moderator google-searches

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#275]
We can save moderators time when data-moderating entries if they don't have to compose the most-common google-search themselves.

Could we add a narrow field to the Sheet with a clickable link to a google-search for "Name + Final Address" ?  (bonus points to have it open subsequent clicks from the Sheet in the same tab)

**Comment by saikatbhadra** [comment]
Hi, can you explain this in more detail? Do you basically want a google link to be automatically generated in the moderator spreadsheet based on the data?
 Can you give me read only access to the sheet?

**Comment by 4kbt** [comment]
Comment-only access sent.

Yeah -- If we had a small cell in every row to click that aggregated data from the "name" and "final address" cells  to 

google-search: name + final_address 

it would buy our moderators at least two seconds per row, probably more.

**Comment by 4kbt** [comment]
The only trickery is that the link-generation can't slow down the Sheet too badly. It might need to use some appscript . @awong-dev  would have some insight there.

**Comment by saikatbhadra** [comment]
I'll take a shot at this tomorrow evening

**Comment by saikatbhadra** [comment]
I'm going to close this for now since the mod workload has dropped, re-open if you think we need this

**Comment by 4kbt** [comment]
Sounds good.
