### ISSUE TITLE
Incorporate call for stories about your donations to index.html

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#278]
Jimmy, in the new index.html design, can you incorporate a call eg "Did you donate PPE? We want to hear what you did!" link should go to https://www.facebook.com/findthemasks which @graemer has claimed and will delegate setting up. 

We will use some of the stories to engage press.

**Comment by cjimmy** [comment]
How about: _Did you donate PPE? We want to hear about it!_
