### ISSUE TITLE
For each country, reset map center position on country

### ISSUE THREAD

**Issue by graemer** [findthemasks/findthemasks#280]
When a user hits findthemasks.com/fr/index.html, the map should be centered on france.

This should be done for:

ca - canada
ch - switzerland
de - germany
gb - united kingdom
fr - france

**Comment by awong-dev** [comment]
On it.

**Comment by drwestco** [comment]
We have methods to set the map view based on the pins. Can we just let the country-specific pins determine the initial map view instead of hard-coding?

**Comment by awong-dev** [comment]
hard coding for now as it's minimal churn. Feel free to update in a PR after if your method is superior.
