### ISSUE TITLE
How many people want email but don't make email public?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#297]
We see a lot of entries where the Instructions include something like "Email for drop-off instructions" or, "Email me", but the only address in the entry is in the private email field.

How often does this happen? We think it happens a lot.

This can be as simple as asking -- how many entries include the string 'email' in the instructions field, but no @ ?

**Comment by marcuscollins** [comment]
Increasingly common. See attached. I suggest a simple validation. I can write a JS snippet if needed to do a regex validator based on the input of the instructions field.

[missing_or_private_email.txt](https://github.com/findthemasks/findthemasks/files/4400331/missing_or_private_email.txt)

**Comment by vdalal** [comment]
Yes, agree.
It will be better if they can provide and we can validate the request vs. their company (hospital) provided email id.

**Comment by saikatbhadra** [comment]
Closing this as I believe we have done the analysis and we have relay now
