### ISSUE TITLE
Add "handmade masks" and "hairnets" to Google form as option for items accepted

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#298]
More hospitals are explicitly requesting handmade masks. 

Also, on the Full Frontal with Samantha Bee TV segment, the founder of GetUSPPE.org mentioned hairnets as an item that hospitals need.

Can both handmade masks and hairnets be added to the checkboxes on the Google form? 

Especially for handmade masks, we are trying to separate free text entry from enumerated in the items field, so adding this as an enumerated item will reduce the number of nonstandard free text requests for handmade masks and make data analytics a lot easier.

**Comment by spitznagel** [comment]
Masks merged into #340.  

Left open for consideration of adding "hairnet" option.
