### ISSUE TITLE
How many recipients have already asked for handmade masks?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#300]
We are seeing the big hospitals start to ask for handmade masks.  What are we seeing in our free-form response field?

**Comment by marcuscollins** [comment]
I will attempt to solve this right now.

**Comment by marcuscollins** [comment]
Left msg on Slack, but right now only 25 total such requests. Will do time series soon, but that isn't much to work with yet.

**Comment by r-pop** [comment]
I have added "Homemade masks (please specific what types)" as a checkbox, so hopefully we'll get better data going forward.

**Comment by marcuscollins** [comment]
@r-pop Thanks. I will continue to monitor. @4kbt Can you close this one?
