### ISSUE TITLE
State filter is broken for France

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#304]
![image](https://user-images.githubusercontent.com/5788989/77810940-90203f00-706d-11ea-80d0-da848854258e.png)

**Comment by drwestco** [comment]
Artifact of having only one state in the data. Worth guarding against this?

**Comment by nburt** [comment]
at some point? Probably not the most pressing thing

**Comment by drwestco** [comment]
Goes towards keeping the filters data in sync with the filter controls and ?state= param. This was bugging me already, so might as well tackle it.
