### ISSUE TITLE
Text change to large donation

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#315]
Instead of:
Have a lot (500+ items) to donate?
We encourage large donors to use another site we work with to help route donations. Register at getusppe.org/give.

Let's use:
Need logistical help or compensation to donate 500+ items of PPE?
Our partners at getusppe.org/give have an intake form where you can register, and a volunteer will get back to you.

This steps down the requiredness a bit, because we still want folks who can have a truck drop stuff off to just do it.

**Comment by r-pop** [comment]
While you're in there, please remove "can't find a site near you" - this used to go to a separate place but just the one getusppe/give pointer is good, and the text above reflects the more recent plan for what that form is for.

**Comment by dhruv4** [comment]
I'll get this one in a bit!
