### ISSUE TITLE
Clarify N95 Mask Types on Google Form

### ISSUE THREAD

**Issue by spitznagel** [findthemasks/findthemasks#340]
This new issue is meant to merge valuable input from issues #11, #82, #148, #298, #299.

Previous issues have suggested adding uncertified PPE, masks that are generally used for construction, and other items. Some hospitals appear to be relaxing their requirements for surgical grade PPE, and some others even encourage homemade masks and other items, however, not all donation locations would benefit from those items.

Additionally, not all donors are familiar with the nuances of surgical grade PPE, or the different certification processes. 

Therefore, I suggest we add the following items to the Google Doc for donation sites as well as links to the differences so that donors can learn about the nuances if they choose to:
![image](https://user-images.githubusercontent.com/8340647/77856237-ad0e5c80-71aa-11ea-9a1f-22f2da21ed67.png)

**Step 1:**
Split "N95s" into 
- N95s Masks (FDA approved for surgical use)
- N95 Masks and similar NIOSH approved respirators (Industrial use, e.g. for construction or manufacturing)
- Homemade masks

*Because the former field item was listed as "N95s," I suggest that all existing data for N95s default to N95s Masks. That category is also the most restrictive.*

**Step 2:**
Add clarifying links for those who want to learn more to the bottom of the "What do you need?" question:
The FDA classifies N95 masks into those suitable for [healthcare use and those for industrial use](https://www.fda.gov/medical-devices/personal-protective-equipment-infection-control/n95-respirators-and-surgical-masks-face-masks#s6). However, the FDA recently issued a [directive authorizing the emergency use](https://www.fda.gov/emergency-preparedness-and-response/mcm-legal-regulatory-and-policy-framework/emergency-use-authorization#2019-ncov) of a broader subset of N95 masks during the coronavirus pandemic, including any N95 mask approved for NIOSH use, such as those used in manufacturing and construction, and some foreign masks certified under different criteria. The latest list of CDC approved masks for coronavirus can be found here:
https://www.cdc.gov/coronavirus/2019-ncov/hcp/respirators-strategy/crisis-alternate-strategies.html

The most recently

**Comment by r-pop** [comment]
Thank you for this synthesis - super helpful. I am also going to talk to getusppe about this soon - my gut is to limit our maker-made PPE involvement to the research-validated designs on getusppe.org/makers (there is some awesome stuff there!)

Cotton mask-covers would be a separate category. They aren't ppe on their own but can be used to protect N95s from stains, prolonging their reuse.

**Comment by r-pop** [comment]
I have left it at one type of N95 mask for now - I agree that linking clarification from the site's static text is a good idea.

I have added "Homemade masks (please specific what types)"

**Comment by vdalal** [comment]
Suggested:
* Have a separate type field for homemade PPE items:
** Homemade items (Masks, Gowns, Booties, Face shields, Overalls  etc.)

**Comment by r-pop** [comment]
Hmm, what we really want to capture is "only masks with filters" vs "cotton masks ok as N95 covers" etc. We could ask analysis what the input has looked like so far - we have been offering the option for nearly a day.

**Comment by 4kbt** [comment]
At this point, this is probably a wontfix? Closing. Happy to reopen if needed.  The primary distinction seems to remain "better than surgical mask" or "surgical mask".  Tomorrow is July. What a strange world.
