### ISSUE TITLE
Expose CSV?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#341]
We've had a request from above to expose our json as CSV. Is that quick/easy?

**Comment by r-pop** [comment]
The task here is to have a GCP function that rewrites data.json as data.csv. 

I can then create a crontab to pull it over to the webserver. 

Then we can link it from the FE UI.

**Comment by marcuscollins** [comment]
See https://github.com/findthemasks/findthemasks/pull/388

**Comment by saikatbhadra** [comment]
This was closed by @marcuscollins  thanks
