### ISSUE TITLE
Add "walkie talkies / baby monitors" to accepted PPE for all countries

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#347]
An increasing number of hospitals are using baby monitors or walkie talkies to limit direct face-to-face contact with hospitalized COVID-19 patients. This help conserve PPE, since short checkups or conversations done over a walkie talkie or baby monitor will not require a doctor or nurse to suit up. 

Hospitals may not have a lot of these on hand, and some may be accepting donations of these items, so we should include it as an item in the checkbox menu of accepted PPE on our forms.

**Comment by r-pop** [comment]
Added!
