### ISSUE TITLE
Search: Remove beta parameters

### ISSUE THREAD

**Issue by patricknelson** [findthemasks/findthemasks#348]
Map search capability is now enabled by default (whenever the map is visible). This issue proposes:

- Removing the `show-search` query string parameter, as it’s no longer needed given it’s already enabled by default.
- Optionally: Removing the `data-enable-search` parameter on the `#map` div, which was only present to facilitate the ability progressively release independently between `index.html` and `give.html`.

**Comment by saikatbhadra** [comment]
@nburt @patricknelson - is this still an issue?

**Comment by nburt** [comment]
I already removed as part of v2 redesign, closing

**Comment by patricknelson** [comment]
Great, thanks 😄 Only created to ensure it's not forgotten. However, while `show-search` has been removed, the full spirit of the ticket isn't entirely carried out. Although not explicitly stated, removing that additional parameter should mean that the `showMapSearch` variable should be brought in line for consistency:

```js
    const showList = searchParams.get('hide-list') !== 'true';
    const showFilters = showList && searchParams.get('hide-filters') !== 'true';
    const showMap = searchParams.get('hide-map') !== 'true';

    // ... some code...

    if (searchParams.get('hide-search') !== null) {
      showMapSearch = searchParams.get('hide-search') !== 'true';
    }
```

Should instead become

```js
    const showList = searchParams.get('hide-list') !== 'true';
    const showFilters = showList && searchParams.get('hide-filters') !== 'true';
    const showMap = searchParams.get('hide-map') !== 'true';
    showMapSearch = searchParams.get('hide-search') !== 'true';
```

And the default initialization at the very top of the file should be _reconsidered_ since it is now only defined there for global access (something I recall being told was discouraged a few weeks back, not sure what the convention has become now).
