### ISSUE TITLE
N95 language shows up twice in map filters

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#365]
See screenshot:

![Screen Shot 2020-03-30 at 10 40 29 AM](https://user-images.githubusercontent.com/2250961/77951660-427b2080-727f-11ea-929b-b44b5244c4b8.png)

I believe the correct fix is the second filter should be just surgical mask (no n95 language).

**Comment by r-pop** [comment]
Correct, second filter should be "Surgical masks"

**Comment by nburt** [comment]
fix here, will merge as soon as translations come back: https://github.com/findthemasks/findthemasks/pull/366

**Comment by r-pop** [comment]
Fixed for en, but I suspect I approved merges in the wrong order because Spanish (and other langs?) are not fixed.

**Comment by r-pop** [comment]
Fixed in IT!
