### ISSUE TITLE
Add "nasopharyngeal swabs" to items list

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#368]
Many hospitals are running short of swabs for taking COVID-19 test samples, and are now using STI swabs or other kinds of swabs for testing. A few hospitals have already written in "nasopharyngeal swab" to the free-response "other" field on the items list.

Although the average person may not have these, community STI clinics/ Planned Parenthoods, etc. could have a supply of these to donate.

**Comment by marcuscollins** [comment]
This is a good suggestion. I would use slightly different language, as I see several other variants: 
```
'Test Swabs': [
        'testing swabs', 'Swabs to test covid-19', 'swabs,', 'swabs', 
        'Quidel 403C Swab Specimen Flocked Tube Flexible Minitip 50 UTM', 'flocked swabs']
'STD. Cotton Swabs': ['sterile cotton-tipped swabs (BD #220531)', 'Sterile cotton tipped swabs (BD #220531)'], 
    'Nasopharyngeal Test Swabs': ['nasalpharyngeal swabs', '6" plastic nasal swabs', 'NP SWABS'], 
    'Oral/mouth Test Swabs': ['mouth swabs']
```
at least some of which are also used for test-sample collection.

**Comment by linderr** [comment]
I second this add. The correct medical term is Nasopharyngeal swabs or "NP swabs" for short --- they are very specific, and not just a long Q-Tip. The swab tip is a special material that swabs AND scrapes (we are testing for virus in your cells to indicate infection, not necessarily surface virus) and the handle must be specific (aka NOT wood) as it messes with the downstream biochemistry.

Currently, due to shortage, other viral test kits are being accepted. Unfortunately for the downstream lab work, I strongly do not think we should offer colloquial terms such as "mouth swabs".  A well meaning human could donate Q-Tips, and although that is nice, is useless for the testing effort.

**Comment by linderr** [comment]
The US Air Force had to fly in 500,000 swabs 2 weeks ago from ... Italy (at it's height =/ )
Copan is an Italian manufacturer.

**Comment by cchang-adi** [comment]
More hospitals seem to be open to taking 3D printed face shields from the community now as well, and grassroots efforts seem to be springing up everywhere. There is need for a centralized database for which hospitals will accept it and what their specifications are, unless OSCMS is keeping a list somewhere that we don't know about.

**Comment by linderr** [comment]
See my post in #general:
https://findthemasks.slack.com/archives/C010HB27BU5/p1585801842227300

A huge 3D print/makerspace/manufacturer network is using our US and CA data
to develop a match algorithm. They have used it to become Shield Net
<http://shield-net.org>. They can currently produce (as a network) ~900,000
face shields per day.

Best,
L

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by crayne** [comment]
I can do this.

**Comment by crayne** [comment]
I'm trying to work on this but am having trouble testing it because of issues involving a local test environment.  Should I just submit a pull request for review without testing?

**Comment by nburt** [comment]
@cchang-adi can this be closed?

**Comment by crayne** [comment]
yes
