### ISSUE TITLE
Setup our website to get search insights to our GA page

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#372]
- [x] Setup Google Analytics: Go to **Google Analytics > Acquisition > Landing Pages > Setup Search Console Data Sharing > Adjust Search Console
- [x] Setup google search console to work with our site:  https://search.google.com/search-console/

@r-pop - I can do this if I get edit permissions to our GA instance. Otherwise you might need to pick it up.

**Comment by saikatbhadra** [comment]
FYI this is lower priority since we don't get much SEO traffic yet

**Comment by nburt** [comment]
@saikatbhadra can this be closed?

**Comment by saikatbhadra** [comment]
Not yet, still working on it

**Comment by saikatbhadra** [comment]
Ok this is implemented
