### ISSUE TITLE
Fire Google Analytics events for key user interactions

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#373]
Generate an event
- [x] if a healthcare worker clicks on the link to add/remove/update a donation site
- [x] if a user navigates to the large donation link
- [x] if a user navigates to the general getusppe.org link
- [x] if a user goes to our Facebook page
- [x] if a user clicks on a map cluster
- [x] if a user clicks on a map marker

**Comment by ngottlieb** [comment]
Tackling this one. Any guidelines for event naming, or should I just pick something succinct and clear for each?

**Comment by saikatbhadra** [comment]
Here's an example of the events I setup:

- Click on state filter (Category: `filters` Action: `states` Label: `name of state`)
- Click on use my location (Category: `map`, action: `center`, label: `user-location`
Each event has a category, action, label, and value (not using that).

Succinct and clear is a good principle. Some more guidance:
- Don't have whitespace in any of your strings for category, action, or label. I would suggest using camelcase since we are using JS.
- Use category to describe the part of the product where the event is generated
- When possible have `action` be a verb (but in cases where its easier to program it with a non-verb that's fine)

Some other tips:
- get access to google analytics from @r-pop so you can make sure your events are firing
- there is chrome extension called Google Analytics debugger which will print to console.log when you fire events which is useful for test
- make sure to turn off your adblocker when testing :)

**Comment by ngottlieb** [comment]
:+1: sounds good, thanks.

I'm just running against my own GA account locally for testing so don't really need access to the official account (@r-pop) but of course it wouldn't hurt for confirming functionality after it's done

**Comment by ngottlieb** [comment]
Submitted PR @saikatbhadra. Not entirely sure on the event attributes I went with, it depends a bit on how descriptive things need to be. I used naming conventions that followed the code (i.e. `noDonations` and `largeDonation`).

Super quick to change the categories or labels (obviously) so just let me know.
