### ISSUE TITLE
Dynamically created donation location number on website

### ISSUE THREAD

**Issue by skimekerr** [findthemasks/findthemasks#376]
It would be awesome to have the number of locations in this paragraph (1700) on the website be dynamically created so that it keeps better aligned with the actual number. Some thoughts...
- should it be per country total or total number of all donation sites across the globe?
- should it be rounded to the nearest hundred or exact number?

=======

How To Donate PPE

Our network of volunteers has created a global map of over 1700+ locations, like hospitals and clinics, where you can donate your masks, gowns, and other PPE.

**Comment by saikatbhadra** [comment]
This will be closed with: https://github.com/findthemasks/findthemasks/pull/607
