### ISSUE TITLE
Make entry-approval flow case-insensitive

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#387]
Right now, entries only go live on the site if the first character in the Approval field is 'x'. Sometimes moderators enter 'X'. Let's make it case-insensitive :)!

**Comment by jamesarosen** [comment]
https://github.com/findthemasks/findthemasks/pull/395/files#diff-1e53ef2f51bd446c876676ba83d7c888R208-R210 addresses this (but isn't merged yet)

**Comment by 4kbt** [comment]
I believe that this is fixed.
