### ISSUE TITLE
Need city-level filters?

### ISSUE THREAD

**Issue by drwestco** [findthemasks/findthemasks#404]
California has ~400 entries. Do we need an additional filter at the city level after selecting one or more states to continue to narrow down the list? The search box above the map helps, although it doesn't affect the list display.

**Comment by saikatbhadra** [comment]
City level filters will be hard for the user (there are too many cities in states like California). I think we should change this request to "make search filters change the list view"

**Comment by linderr** [comment]
Yes, ideally the text list should match and only list sites that is being shown on the map.

Use "Mills Memorial Hospital Terrace" in Terrace, BC on the map to test out this function. It's the only pin for hundreds of kilometers

**Comment by cchang-adi** [comment]
I agree that changing the list to match what's on the map is an excellent idea.

**Comment by saikatbhadra** [comment]
I'm going to close this since filters are being superseded by map usage for now. @tinabeans please take note of this use case (being able to see in list view what donation sites are in your city)
