### ISSUE TITLE
Ignore whitespace before/after city names (prevent duplicated city headings)

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#408]
If there is an additional whitespace around a city name, the site behaves as if it's' different from the same city name with no extra whitespace. 

ie "Woodland Hills " is different from "Woodland Hills"

Unfortunately, trailing whitespace seems to happen a lot with these form fields. This generates what looks like two repeated city headers for the same city.

The only fix presently is manual removal of the extra trailing space. 

Would it be possible for the site to ignore whitespace before/after (especially after, though there are some spaces before) city names when deciding how to cluster individual listings under cities?

**Comment by raindrift** [comment]
Yeah, should be straightforward. I’ll take care of it in a few mins.

**Comment by raindrift** [comment]
Hm. This already seems to be happening. Do you have an example of a city that's duplicated so I can go figure out what's happening with it?

**Comment by crayne** [comment]
I'm working on fixing up the city names for the boroughs of Manhattan in #218 , and I've found some duplicates which I was going to fix manually - but now I won't do that because of this issue.  BTW there are two cities named "New York" in the listing, and I suspect that it is a manifestation of the whitespace problem.

**Comment by drwestco** [comment]
We trim the city and state values when parsing the downloaded data. There shouldn't be any duplicates on the site due to leading/trailing whitespace:
```
    const state = entry[stateIndex].trim().toUpperCase();
    const city = entry[cityIndex].trim().toLowerCase();

**Comment by cchang-adi** [comment]
I just realized that the site display is not faithful to the HTML that our "reload sheet data" script puts out! The final output is indeed trimming whitespace and doesn't have this problem, but the "reload sheet data" output is not doing that, which is why I was confused. Up until now everything in the "reload sheet data" output was faithfully depicted on the site, but this is a difference. My bad for not checking more thoroughly, thanks @raindrift for looking into it.
