### ISSUE TITLE
Add a quantity field for at least face shields and masks

### ISSUE THREAD

**Issue by TimmyV117** [findthemasks/findthemasks#409]
I'm working with a Chicago branch of Helpful Engineering and we are trying to connect Hospitals with various 3d printers/makers of face shields and masks. The current form of the data gives us a sense of who needs what but it doesn't give us a sense of quantitative demand. Can estimated quantity fields be added for at least the face shield portion? This will help us scale our production and meet demand much faster.

**Comment by linderr** [comment]
Hi Timmy,

One of our collaborators just launched a new matching service called Shield Net: https://shield-net.org/ I would recommend getting directly in touch with them as they have these types of numbers. In fact, you can just join their US-CA network of makerspaces and manufacturers as a collaborator directly and they will help you with matching your donations to requesting sites.

We have recently shared our data with them and they are working on curating all sites requesting face shields on Find the Mask US and Canada to a subset who is able to accept 3Dprinted/maker shields. Please keep in mind some clinics and hospitals are bounded by pre-existing risk management policies and not every site requesting face shields may be formally allowed to accept makermade items. 

If you want more information: Shield Net grew from the Badger Shield initiative between UW Makerspace and UW Hospital. If you take a look at their partners, they have amassed a powerful network of commerical manufacturer who will print their design including Delve, Ford, Engineers without Borders, Trek, Microsoft as well as university campuses and well-meaning organizations such as yours. https://making.engr.wisc.edu/shield/

Their network's daily output as of April 1 is over 800,000 shields per day. And sounds like it will only grow with your help.

Once Shield Net curates our list, we aim to re-integrate that under a "Face Sheild - 3D printed/manufactured" option as a listable and fiterable item.
