### ISSUE TITLE
Expose Categories in json / CSV

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#420]
We have categorization information that our data-consuming partners might be able to use. Even if we're not displaying it on the main site (which I think we should do, too), we can make it available for analysts.

The relevant column is  ( "Type of organization?" , "org_type" ). 

Exporting this should be as easy as adding a column to the data-exports, I believe?

**Comment by crayne** [comment]
@marcuscollins I would like to do this -- I notice that you wrote the original code to save the csv file.  I located it in index.js.I would like to examine the data before it is saved to see where to add Category.  Can I run this code to test it?  Where would the console output appear?  Thanks.

**Comment by saikatbhadra** [comment]
This is done now
