### ISSUE TITLE
Thank corporate sponsors

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#433]
Some companies have been really generous in donating 10s of thousands of dollars worth of services to us. Thinking we add a logo + line on what they donated on the whoweare.html page.

[Smartling](https://github.com/findthemasks/findthemasks/issues/432) - Access to their translation management system

[Google](https://google.com) - Free Google Maps API credits

[Slack](https://slack.com) - Free Pro account

@r-pop am I missing anyone else?

**Comment by nburt** [comment]
Took a stab at this here: https://github.com/findthemasks/findthemasks/pull/442

**Comment by ngottlieb** [comment]
should we close this issue @nburt?
