### ISSUE TITLE
Map-zoom on search is too tight

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#436]
When searching for a state, the Map view, at least sometimes, zooms in too tightly.

When searching for "California", it picks out a few pins near Fresno. "Texas" favors a few points near Dallas. This one might be tricky to fix.

![image](https://user-images.githubusercontent.com/3980568/78368912-3e9a1780-7579-11ea-8366-5a7be90ed15f.png)

**Comment by 4kbt** [comment]
Happens on mobile, too.

**Comment by ngottlieb** [comment]
this is actually kind of an interesting situation, I think. Basically, the search isn't really being executed by our code but by a separate service, and we don't know whether the person typed in an address, city, or state. Google (the geocoder service in question) returns a recommended viewport that might solve this problem, but what we're doing right now is centering the map on the closest existing markers to the exact coords that are returned: https://github.com/findthemasks/findthemasks/blob/master/public/locations-list-map.js#L751.

I don't have the project knowledge to decide how to proceed on this. One possible but slightly complex solution would be to attempt to use Google's "recommended" viewport then expand it to include the nearest markers (if it doesn't already include any)?

**Comment by drwestco** [comment]
I like suggestion 2. Use goog's suggested viewport, expanded with our current "3 nearest markers" logic. If the viewport starts out wide enough, it won't expand.

**Comment by nburt** [comment]
@ngottlieb just fixed this and I merged which closed the issue. @4kbt let us know how it's working for you and you can reopen the issue if there are still some problems

**Comment by 4kbt** [comment]
Looks way better. Awesome.
