### ISSUE TITLE
Search from international countries can return the wrong results

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#453]
Search results seem to bias towards the US. For example, when on https://findthemasks.com/fr/ and you search 13000 (postal code for the Marseille area) the map zooms out to focus on France + US. It seems to have found a US result and then zoomed out to include 3 French markers.

One thought is that we can try to append the country code from the url into the search (13000 fr does return the correct result). Would need a little experimentation though and there might be cases where you wouldn't want to necessarily append the country to the search.

Somewhat related is what should we do when a user is on the US site and they search for Paris, France? Currently we'll zoom out so that Paris is in the viewport as well as the nearest 3 US markers. Is this correct? Even if they're on the "US" site would we want them to be able to search in France?

**Comment by saikatbhadra** [comment]
In my view every user should be able to see every donation site. We have no idea what their use case is. One example is they could be on a VPN and so their locale was selected in a country that is not where their VPN is.

**Comment by nburt** [comment]
ok I think I have a solution to fix the postal code issue. We're defaulting to US as the region even if the country is FR. I think there's still some zooming work to be done at some point but I think that correctly setting the region is good enough for a start
