### ISSUE TITLE
#data-ca Email and telephone data don't output on Combined tab from raw data (Columns Q to T)

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#464]
In the new MergeConfig style spreadsheets, identifier rows on Combined are missing in Columns Q through T. Corresponding data in this row (email, telephone etc) are not being outputted from raw data tabs. See row 146 (email missing) and test row 147 (email and phone missing):

![image](https://user-images.githubusercontent.com/62862914/78505279-51524f00-7727-11ea-8138-496f9c2b7d3b.png)

**Comment by linderr** [comment]
@nburt @awong-dev easily work around for now, so check whenever you're free!

**Comment by nburt** [comment]
I think adding code headers to the response sheets for each country would copy over everything correctly.

My understanding is that we left these blank intentionally for now and were going to follow up. Doesn't the script that creates data.json pull every column with a "code" header? I think we left these blank until we figured out how to build the data.json file using code headers while also making sure we aren't returning identifying information

@awong-dev Is that correct? I think that ideally we should filter out data that we need to while building the json but combined sheets would include everything

**Comment by linderr** [comment]
Not sure if helpful but: the original version of your MergeConfig code did transfer the entire row. See row 114 and above.
Submitted emails, telephone numbers all there.

It is necessary in the modding process to be able to reference the email and telephone on the same line. Sometimes, users make logical assumptions. They fill out e-mail as the very first field on the Google Form and tell you later "Please email me for donations" but do not include their email in the Instructions field. Because we don't publicly share any emails unless stated, we will manually edit "Please email me for donations: Bob@hospital.ca" etc.

**Comment by awong-dev** [comment]
The problem is we want them out of data.json.  The solution is as you said, adding the header rows. But before that, we have to modify functions/index.js to filter them out based on some pattern.

I was thinking anything with a leading underscore would just get dropped in the data.json production.

Thoughts? If that looks good, I can try to write up tonight (or someone else can if they want)

**Comment by nburt** [comment]
Yeah leading underscore sounds great to me. I think we've done some work to freeze and permission header cells already but probably worth implementing that for all sheets so that personal info isn't actually leaked

**Comment by awong-dev** [comment]
Done for canada and cloud function update deployed.
