### ISSUE TITLE
Set up ENV variable configuration of gmaps API key on heroku

### ISSUE THREAD

**Issue by ngottlieb** [findthemasks/findthemasks#465]
This will allow us to use a separate dev API key for review apps, making them actually functional.

Some thoughts on this (having not dived in yet):

- implement using `postdeploy` shell script to replace API key in code with ENV var
- how to handle local development which won't have a `postdeploy` script being run? (probably the answer is leave an API key in the code as it is right now and just overwrite it with the post-deploy script)

Need access to Heroku and a FindTheMasks dev API key to fully implement

**Comment by maplebird** [comment]
This is now tracked in #495
