### ISSUE TITLE
New Feature Request: Stale/Expired sites become Greyed Out

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#466]
Everyone in #findthemasks has done amazing so far! **Let's not see an empty map at the end** when the pandemic is over :)

**Derek has coded the dimming script** and made icons small circles instead of big pins for use to display data meaningfully in global sites as well as when a State filter is on.

**As we get requests to remove listings because healthcare sites have enough PPE, instead of a full removal, let's just literally grey them out.** This would indicate this site once was accepting donations but no longer is. We will add generic text in “Instructions” from the data mod end stating something like “This location has enough donations for now! Consider the nearest colored pin, thank you!” etc. 

**Another way to use this feature** would be as entries "expire" if they are more than N days old (but keeping the info available) would help highlight newer submissions with current needs. That will allow donors to shift behavior to prioritize more certain needs.

Full takedown requests (request to be removed from database) for various reasons (legal restrictions, erroneous submission etc) will still be honored and manually unpulished by data mods and will not appear on our map at all.

**Comment by 4kbt** [comment]
At the moment, we don't have a way to track unique sites (rather than submissions) that were once approved, but are now removed.
Perhaps we should add a removal code for the day that we start seeing them taken down because they're actually fully-stocked.

So far, we have none of them, though :disappointed:, only grumpy people who don't want us listing them anymore, or people who have simply asked to have the listing removed without comment.

**Comment by 4kbt** [comment]
I have added the removal code "P" to designate sites that have been removed because they have enough PPE.

**Comment by andysaurin** [comment]
Please think of European sites under GDPR regulations - if they want to be removed from the db, they must be removed, not simply flagged as such

**Comment by linderr** [comment]
@andysaurin definitely. Requests for removal of the database was what I meant by "full takedown requests". They will not be visible at all.

**Comment by linderr** [comment]
@drwestco would you consider looking at this? Sorry to assign you without asking, getting used to GH ^_^!

**Comment by linderr** [comment]
@andysaurin edited the write up to make it more clear on that point, thank you!

**Comment by saikatbhadra** [comment]
I am closing this as we will not want to show dimmed out pins for takedown requests due to privacy related reasons.

**Comment by linderr** [comment]
lol we are still talking about this in N95 Google doccccc
