### ISSUE TITLE
Accepted item filters run onto 2 lines on mobile

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#481]
I recently made a change to do a 1 for 1 mapping of form enums to filters. There are a few new ones with some explanatory text in them that break onto 2 lines on mobile. I think we could remove the explanatory text for the filters

![Screenshot_20200406-084457_Brave](https://user-images.githubusercontent.com/5788989/78561252-668db300-77e5-11ea-9e6f-17bd8d9ef587.jpg)

**Comment by ngottlieb** [comment]
@nburt I think this was solved (as much as it can be solved) by the change I just made in PR #546 to exclude the parenthetical clause. We could also always tweak these further by just changing the `en.json` translations to be shorter.

Can I close this issue, or do you think the long ones ("Face Shields - 3D-printed or makerspace") should still be thought about / modified?

**Comment by nburt** [comment]
Yeah I think this is fine
