### ISSUE TITLE
Filters should be dynamic by country

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#493]
Different countries have different accepted ppe in their forms. We need to make the filters that appear below the map dynamic so that, for example, walkie talkies don't appear in France where they are not in the form.

**Comment by nburt** [comment]
https://github.com/findthemasks/findthemasks/pull/494

**Comment by ngottlieb** [comment]
this is a dup with #402 , right?

I talked about this with @nburt a little bit the other day but I'm still not clear on why the option @awong-dev alluded to in #402 isn't the right one to take at this point: dynamically generating filters based on the list of elements that's being displayed. I don't *think* it would need to be scraped after rendering, either, right? We just use the same list of elements in the JS and compile unique filter items and then `i18n` them the same way we do for displaying them in the list/marker templates?

**Comment by nburt** [comment]
The one tricky thing here I think is the "other" field. We will want to make sure we aren't generating any filters from that and I don't have a great idea as to how to solve that problem since it is a free form field

**Comment by ngottlieb** [comment]
Ah I see what you're saying @nburt -- we allow people to add basically anything, but we don't want to filter on things that aren't actually in the canonical list. Hmm. I mean, we could maintain a comprehensive multi-language whitelist maybe?

**Comment by nburt** [comment]
Yeah I think that would help to have one sheet of our canonical language. In practice I think it will be hard to ensure it's always aligned perfectly but maybe worth a shot?

**Comment by ngottlieb** [comment]
@nburt I'm going to give this a go, my approach is going to be:

-- establish (hardcoded) country by country whitelist of filter items (with a default set)
-- detect categories of items for filtering by searching the dataset we're displaying, but limit categories to those in the whitelist

**Comment by ngottlieb** [comment]
actually, maybe the whitelist doesn't need to be country-specific -- the only situation we would worry about that could prevent is if one country doesn't list an item as an actual donation, but another does, and someone types that item name in the `Other` field? Seems like not that big an issue?
