### ISSUE TITLE
nodeJS conversion

### ISSUE THREAD

**Issue by maplebird** [findthemasks/findthemasks#495]
This is a general tracker for nodeJS conversion.

Advantages:
* Extremely easy to deploy the app in Heroku and have it automatically build on push to master
* Way more people here are familiar with JS than PHP (which as far as I can tell from the code we’re not using much)
* Use routes instead of .htaccess
* Easier to run locally (`npm install` followed by `npm start`)
* Ability to use env vars for config
* Dynamically grab `data-${country).json` files
* Generate meta tags by location

Current outstanding tasks:
* ~~Get donation forms to work~~
* ~~Router for symlinks~~
* ~~Use template language for generating html~~
* ~~Grab `data-${country}.json` files from bucket~~
* ~~Enforce TLS~~
* ~~Update documentation~~
* ~~Dockerize app~~ (not strictly required but some people asked for it)
* Use node routes to cache data-json files instead of directly linking to bucket (will be tracked in a separate issue/PR)

Working branch - #490

**Comment by maplebird** [comment]
This also takes care of #465

**Comment by ngottlieb** [comment]
So -- one further thought on this. Team Canada wants to add some more text to the landing page in a way that won't fit with existing headings, and talking about it with them and just thinking about it more, this sort of thing -- changing the landing page more than just changing text -- is likely to be needed across most if not all countries.

That alone seems like a pretty strong argument in favor of a templating engine. I think we could accomplish this with a Jekyll-based approach, too, but using Node and Handlebars (or some other templating engine) perhaps allows us to be a bit DRYer and fall-back to default content without duplicating it.

**Comment by nburt** [comment]
@ngottlieb I added express moustache last night, do you think that works well for us? Later today I was going to move the /config.js call to use the local variables + template instead as well

**Comment by maplebird** [comment]
PR #495 has been merged and new site is now live in Heroku. Marking this as done.
