### ISSUE TITLE
Share links so users can share our site to their social networks

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#498]
We should have share button links across networks (Facebook, LinkedIn, Twitter, Reddit) so users can share the site and bring in their own networks.

**Comment by saikatbhadra** [comment]
@susanashlock  - I am not sure I did a good job of explaining this feature so  what I am looking for are buttons where a user clicks and it generates a message for them to post to their network.

So user clicks on Facebook link, it opens a new tab and they get a link to Facebook with a filled out  post to their timeline. Something like "Find out where you can donate PPE at findthemasks.com" (Talk to #comms for a better message). The user would be able to edit that message and then post to their timeline. Same goes for LinkedIn, Instagram, whatever networks the cool folks are into nowadays.

I don't want these links to go to our social pages because that doesn't drive traffic to our sites.

**Comment by saikatbhadra** [comment]
Oh and ideally we should have google analytics linked to the click of these buttons, but its definitely just a nice to have (not a blocker).

**Comment by crayne** [comment]
Merged
