### ISSUE TITLE
Setup a monitoring tool to get javascript errors

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#499]
As a developer, I would like to be alerted on when my users get javascript errors.
- sentry.io
-

**Comment by saikatbhadra** [comment]
Sent emails to a few of the vendors, probably going to go with the one that offers us the best free account.

**Comment by drwestco** [comment]
Dup of #462 ?

**Comment by saikatbhadra** [comment]
whoops...

Duplicate of https://github.com/findthemasks/findthemasks/issues/462
