### ISSUE TITLE
h2 tags should not have capitalize applied to them because different languages have different casing rules

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#504]
US title casing differs from other languages. e.g. in French you only capitalize the first word in a header.

We need to update strings to fit the country casing rules + remove the capitalize css

**Comment by ngottlieb** [comment]
will change the CSS, but @nburt question re: translation -- when we change titles, will Smartling always re-translate them with first-letter capitalization as we do in the US, meaning we'll have to fix it, or will it learn the capitalization differences?
