### ISSUE TITLE
Non-code: call hospitals and input donation info for geos not yet covered

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#51]
Volunteers could call hospitals in states and major cities not yet covered, and input info through the form.

**Comment by r-pop** [comment]
or email! @yauwong wrote a temple and can post here.

**Comment by liamrosen** [comment]
I've worked in sales for the past six years, prospecting and making up to 40 cold calls a day. Happy to help.

**Comment by saikatbhadra** [comment]
@liamrosen Louisiana is hit bad and we only have 20 hospitals right now. Here's a list of hospitals in the state:
https://www.ahd.com/states/hospital_LA.html
https://www.officialusa.com/stateguides/health/hospitals/louisiana.html

**Comment by saikatbhadra** [comment]
@r-pop  should we close this?

**Comment by saikatbhadra** [comment]
There's no AI here for a dev to close on, so I'm going to close this but I should note this is a good idea esp in countries/regions with low coverage. @linderr - you might want to consider adding a section in "Join Us" to cover this kind of work.

**Comment by linderr** [comment]
@saikatbhadra yup we do this in Outreach teams --- I think it's b/c we're also using GH as a product management notebook/place holder --- so not all Issues are AI/dev stuff, sorry!

**Comment by linderr** [comment]
^ But I will put it in my playbook for sure for new #i18n groups who are coming on board now :) thanks!

**Comment by saikatbhadra** [comment]
I think it's fine to have non technical tasks as long as they are specific up to be closeable. So for example, "call up 10 hospitals in x area to see if they need to be on the map" would be something.
