### ISSUE TITLE
Add contact info row

### ISSUE THREAD

**Issue by liamrosen** [findthemasks/findthemasks#52]
It would be good to have a contact info row so people could contact the hospitals with questions (i.e. one I've been asking lately is "do you accept 3D printed masks or face shields?"). Even if it was optional, as I'm sure hospitals are way too busy right now to answer a lot of questions.

**Comment by r-pop** [comment]
We are letting hospitals decide whether to add contact info. many have! it's folded into the instructions usually.

**Comment by liamrosen** [comment]
In that case, how about changing the instructions form question from: "Drop off instructions, eg curbside procedure or mailing address ATTN: instructions:" 

to something like:

"Drop off instructions, e.g. curbside procedure, mailing address, contact person/information"

**Comment by r-pop** [comment]
Done, thank you!

**Comment by r-pop** [comment]
I had to revert this, it broke the parser we are trying to launch.

**Comment by awong-dev** [comment]
obsolete.
