### ISSUE TITLE
[UI] Move geographic center of Canada Westward for default mobile view

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#520]
The default mobile map view of www.findthemasks.ca has most of our pins (cluster of 137) hidden on default view due to the placement of the [+/-] zoom buttons. 

Considering mobile can be up to 80% of our views according to some previous data by @saikatbhadra, it is important to present a default view that instantly displays our data as a whole. 

**Left: default mobile view currently - Bulk of data (137 sites) hidden behind zoom buttons**
**Right: suggested view choosing a more *Eastward* center to _act_ as it the geographical center of Canada** to achieve a Westward frame/panned effect.
![image](https://user-images.githubusercontent.com/62862914/78851014-98fa0480-79cd-11ea-9f99-67e50b9ebb93.png)

**Comment by ngottlieb** [comment]
just to clarify...I *think* you mean moving it east @linderr? 🐙

**Comment by ngottlieb** [comment]
I tweaked it, you can confirm if it looks better for you here @linderr:

http://20b9a25b.ngrok.io/ca/

**Comment by linderr** [comment]
@ngottlieb I see what you mean here. Yes, to set the centre lat/lng more Eastward to achieve a Westward "pan" :) Thank you!

**Comment by linderr** [comment]
My mother caught it. She says, "great!" lol.
