### ISSUE TITLE
data-fr sheet no longer being populated by lat/lng values

### ISSUE THREAD

**Issue by andysaurin** [findthemasks/findthemasks#529]
Hi guys,
we're about to launch the french FTM site and decided to do some real address submits but the lat/lng values aren't being populated after approving - see screen with lines 25 (Ewa approved) and 29 (my approved)

Any ideas??? Launching with sheet that doesn't populate lat/lng would be a disaster to say the least!!!

Cheers for throwing an eye the issue
Andy

<img width="1281" alt="Screenshot 2020-04-10 at 18 32 39" src="https://user-images.githubusercontent.com/18532832/79006876-57e32b00-7b5a-11ea-9633-e680b3e7cb36.png">

**Comment by andysaurin** [comment]
Manually entering the lat/lng while this gets fixed and reloading the sheet with
https://us-central1-findthemasks.cloudfunctions.net/reloadsheetdata/fr

doesn't specify the entry on the gMap :(

line 25 has had its lat/lng values entered in the sheet: 43.408961  5.215514
And it should show on our map within the cluster of sites south coast (there are currently six sites in this cluster - this should make it 7)

<img width="1281" alt="Screenshot 2020-04-10 at 19 09 58" src="https://user-images.githubusercontent.com/18532832/79009138-228d0c00-7b5f-11ea-8503-7276dcf41db5.png">

**Comment by andysaurin** [comment]
note to add, manually entering the lat/lng values and reloading sheet works - the pin appears on the map, so no problem in either data entry/export directions

**Comment by andysaurin** [comment]
I just learned we have to manually pull this with https://us-central1-findthemasks.cloudfunctions.net/geocode/fr

**Comment by linderr** [comment]
@andysaurin likewise for the CA sheet --- unclear what happened! We had a fully functional submission until yesterday afternoon. Three hours later, an evening entry failed for both Final Address and lat/lng

On the CA sheet we are just doing this manually now: https://us-central1-findthemasks.cloudfunctions.net/geocode/ca

**Comment by susanashlock** [comment]
Copy/pasting comment from #534 here: 

The script that populates the lat/lng now runs every 5 minutes.  It will add lat/lng for any row that has 'x' in "approved" column and is missing lat/lng.  I just tested this in the [FR spreadsheet](https://docs.google.com/spreadsheets/d/1YGWlGPOfJFEsUP6VTFCVohlsHxKMYA5HppatbLwNBVk/edit#gid=1291956074) and verified that if I delete the lat/lng in the last row, the lat/lng is re-populated within 2 minutes

**Comment by andysaurin** [comment]
Thanks Susan, all functionality has come back on board \o/ 
Closing ticket
