### ISSUE TITLE
data-ca sheet no longer being populated by lat/lng values

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#534]
Same issue as [#529](https://github.com/findthemasks/findthemasks/issues/529) below.

**The automation of both the Final Address and lat/lng to run on the sheet is broken.**

Manual refresh of [geocode/ca](https://us-central1-findthemasks.cloudfunctions.net/geocode/ca) forces published rows marked by "x" in Column A to populate the three columns: **final address, lat, lng**
![image](https://user-images.githubusercontent.com/62862914/79030548-557ad400-7b4e-11ea-9db6-fc949c8aa7b0.png)

**Unclear how this became unlinked but would greatly appreciate it being re-automated.** It really helps during the data moderation process, thank you!

**Comment by susanashlock** [comment]
The script that populates the lat/lng now runs every 5 minutes.  It will add lat/lng for any row that has 'x' in "approved" column and is missing lat/lng.  I just tested this in the CA spreadsheet (https://docs.google.com/spreadsheets/d/1STjEiAZVZncXMCUBkfLumRNk1PySLSmkvZuPqflQ1Yk/edit#gid=465803002) and verifying that if I delete the lat/lng in the last row, the lat/lng is re-populated within 5 minutes.

**Comment by linderr** [comment]
@susanashlock okay, understood about the lat/lng columns!

How about the re-population issue with Final Address? See row 235

**Comment by linderr** [comment]
Fixed! Thank you @susanashlock and @awong-dev ! Closing
