### ISSUE TITLE
Cache data-country.json files via node router

### ISSUE THREAD

**Issue by maplebird** [findthemasks/findthemasks#535]
To prevent constant hits on the bucket (and potentially hitting API rate limits on free tier), we should instead proxy the files via node router.

This way they can also be cached via CDN.

**Comment by nburt** [comment]
@maplebird do Albert's new route + this PR: https://github.com/findthemasks/findthemasks/pull/557 solve this issue?

**Comment by maplebird** [comment]
@nburt Yep just saw the code this morning, #557 solves this.  Resolving.
