### ISSUE TITLE
Add link to Mask Match in "How to Donate PPE" 

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#561]
Mask Match has reached out to form a partnership, and we've agreed to mutually link each other's sites.

They would like to be included in the "How to Donate PPE" section on our landing page. Suggested text:

**Want to mail your masks?** 
Our partners at https://www.mask-match.com/ can help.
 

BTW - if we're editing the front page, there's a missing link at the very bottom of this section, at 

**Have you already donated?**
Tell us how you helped by posting on .

**Comment by linderr** [comment]
Also putting together a Collaborators page where we could list them again! :)

**Comment by saikatbhadra** [comment]
Is mask match international?  If not please list the countries to show for
this link.
-- 
-Saikat
saikat.bhadra@gmail.com
(832) 654 1735
https://www.linkedin.com/in/saikatbhadra

**Comment by linderr** [comment]
Pretty sure it’s only US. @cchang-adi ?

**Comment by cchang-adi** [comment]
From their FAQ page, it seems they’re mainly US and Canada, with some partners in Brazil and Finland. https://www.mask-match.com/faq

**Comment by linderr** [comment]
That's awesome! We need a Brazil and Finnish team :)

**Comment by saikatbhadra** [comment]
This is closed, thank you @ywyw

**Comment by linderr** [comment]
hahah nooo.
