### ISSUE TITLE
Change default desktop view of Canada and shift geographic centre South

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#564]
The default zoom level of Canada is too far out --- it overly clusters pins so it looks like Manitoba is empty of requesting sites when it's not. 

![image](https://user-images.githubusercontent.com/62862914/79097933-c9b3a400-7d15-11ea-9e49-821ac3a2cb21.png)

To achieve this view, we need to zoom in and to move the geographic centre of Canada Southward to effectively "pan North" in the Frame and make sure Toronto points are still in-frame.

**Comment by linderr** [comment]
@ngottlieb You were able to do this for mobile --- are small screen and large screen default views separate or linked?

**Comment by ngottlieb** [comment]
They are the same code. I played around with this a bit and we can't increase the zoom without ruining the view for mobile. Also unsure about excluding Canada's north from the default zoom...I know we don't have sites up there (yet) but...

I don't immediately see a way of customizing the marker clustering behavior to solve the Manitoba issue, but if there's someone with more extensive knowledge of the Google Maps API maybe they will have an idea...

**Comment by linderr** [comment]
We can leave this for the UX re-design since the desktop and mobile versions will be different.
I believe the logic is to set a screen-size upfront. If small screen, x settings. If not-small screen, y settings.
Then we can parse out the default settings that make sense for each screen size

**Comment by linderr** [comment]
Replaced by [#633](https://github.com/findthemasks/findthemasks/issues/633) for v2!!!!
