### ISSUE TITLE
Text Change for give.html [FTM global]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#570]
Please change text under embed map on give.html to:

**"In collaboration with [#findthemasks]. Don't see your healthcare facility listed? Fill in our [PPE Request Form] to join the map!"**

**[#findthemasks]** will link to the country-specific homepage that corresponds to the respective give.html page:
give.html links www.findthemasks.com
/ca/give.html links www.findthemasks.ca
/fr/give.html links www.findthemasks.com/fr _etc_.
**[PPE Request Form**] can remain the button to the respective country's request Form.

**We no longer need to stay unbranded**. In fact we need some marketing/branding assistance and with increased embedding from our existing partnerships and collaborators, this text-change is necessary. People reach out to us to discuss how to collaborate on the "GetUsPPE map". We all worked hard to make this global PPE needs map. Let's let the world know about Find the Masks!

**Comment by linderr** [comment]
For example some collaborators have replaced their entire donation site pages with our map: https://maskaherobc.ca/ppe-for-hospitals. Their visitors will have no idea about us

**Comment by awong-dev** [comment]
This doesn't mention takedowns. Do we need language for that?
