### ISSUE TITLE
Set default language for each country?

### ISSUE THREAD

**Issue by drwestco** [findthemasks/findthemasks#572]
If there's not an explicit ?locale=xx param, the language should probably be set based on country:

Austria: German
Canada: English
France: French
Germany: German
India: English
Italy: Italian
Poland: Polish
Portugal: Portuguese
Spain: Spanish
Switzerland: German
UK: English
US: English

**Comment by raindrift** [comment]
If there’s not an explicit locale, the language should currently be set
using the browser’s language setting. This is usually a more accurate
indication of what the user prefers to speak.

If that isn’t working, it’s a bug. Our i18n library definitely supports it
and it was working last week. :)

**Comment by drwestco** [comment]
That's a fine approach too!

**Comment by nburt** [comment]
+1 to the browser language. Going to close this but reopen if it isn't working.

Currently the logic for choosing the language is `locale` param -> browser detected locale -> 'en'
