### ISSUE TITLE
data-us.csv is gone

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#576]
In the past, we surfaced a CSV export of our US dataset at data-us.csv  (or perhaps data.csv). This morning, one of our partners reported it missing.

Can we bring it back? (Also, org_type was missing from CSV in the past, can we make the CSV columns match the json columns?)

**Comment by ngottlieb** [comment]
this has to do with our transition to a Node server, I'll give it a go

**Comment by 4kbt** [comment]
If you're able to make it go, ping the thread in #analysis so that our partners at Northwestern can pounce on it when it is ready :)!

Thank you!
