### ISSUE TITLE
Bare links for sites break mobile pages in index-automated

### ISSUE THREAD

**Issue by ctavispost** [findthemasks/findthemasks#59]
Links should be placed in tags like:

`<a href="[link]">donation info</a>`

**Comment by r-pop** [comment]
sounds like a data cleaning issue? @skimekerr @cchang-adi

**Comment by skimekerr** [comment]
Got it. I'll update.

**Comment by skimekerr** [comment]
Links should all be updated now.

**Comment by cchang-adi** [comment]
We reverted to plain text but never went back to tags. Should we try those again so they're easier for users on mobile (hard to copy-paste and then open)?

**Comment by r-pop** [comment]
Ok with me to try again, as long as you test and revert if anything goes
wrong.

**Comment by spitznagel** [comment]
@cchang-adi - it seems like the site still works on mobile and that all the links I've checked are properly tagged on the site. Is this still an outstanding issue?
