### ISSUE TITLE
Updates to whoweare.html

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#60]
Need to credit all of the last ~24 hrs volunteers! Please reply with how you'd like to be acknowledged (eg how to write your name), and optionally a link to your internet presence.

@eZanmoto @skimekerr @marcpopmsft @unruthless @alexisjulia @melaniebcohen

Also we should update this page with a link to the PPE TO CROWDSOURCE sheet to acknowledge their contribution to gathering the data we display

**Comment by eZanmoto** [comment]
I'm Seán Kelleher, and I'm eZanmoto on most platforms but @sean_m_kelleher on Twitter. Thanks very much!

**Comment by melaniebcohen** [comment]
Just Melanie Cohen is fine, rebuilding my website at the moment. Thanks!

**Comment by r-pop** [comment]
@cjimmy please let me know how to add your name and optionally what link to include.

Others who haven't answered me, ping. :)

**Comment by cjimmy** [comment]
Full name, Jimmy Chion, and link to github account @cjimmy is great.

**Comment by saikatbhadra** [comment]
@r-pop  on the dev side, do you want me to just to link to the github contributors page since that will be up to date and accurate?

**Comment by vdalal** [comment]
Vasu Dalal (https://www.linkedin.com/in/vasudalal/)

**Comment by r-pop** [comment]
@saikatbhadra yes please, I have obviously not kept up with manual edits. 

For other manual edits, please submit PR and add yourself as you wish.

**Comment by saikatbhadra** [comment]
Closing this, if you would like your name added to the project, please directly edit the whoweare.html in github and then submit a pull request.
