### ISSUE TITLE
Create a Volunteer/How Can I Help? page

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#602]
I'm imagining something like findthemasks.com/volunteer 

We keep getting requests for people to help us out. Having a central location for us to advertise timely needs and for prospective volunteers to visit might help us to keep it organized, both internally and externally.

Strawman sections:

Thank you!: Thank you for your interest in helping FindTheMasks, etc.

Needs: enumerates current needs for volunteers

Contact: Provide a simple contact form for prospective volunteers to register their interests, time-availability, and skills.

**Comment by linderr** [comment]
I agree! Stefanie, Jane and I are working on the About, FAQs, Partner and Join Us pages for text/content. I noticed that the "Join Us" real estate recently got replaced by the Share dropdown in v2.. @tinabeans where shall we put the volutneer page @4kbt is suggesting now?
https://findthemasks.slack.com/archives/C010J52HXPD/p1586910401413400?thread_ts=1586462363.328900

**Comment by saikatbhadra** [comment]
I've setup a skeleton page. I filled out the dev section, can I get some other content?

**Comment by linderr** [comment]
@saikatbhadra can you DM me your gmail on Slack? We are working on content for all the new subpages but waiting for new UI/UX dev HeatherQ to mock up designs this weekend
