### ISSUE TITLE
Add map navigation query params that allow sharing links to places

### ISSUE THREAD

**Issue by ngottlieb** [findthemasks/findthemasks#603]
Adding:

- `q`: a map search query
- `coords`,`zoom`: obvious enough

There was some discussion about whether `lat,lng,zoom` could just be passed as the `q` param. I'm not so sure about doing this. If you search `lat,lng` in our existing search, it works. But I'd like `q` to leverage our existing search mechanism, while specifying `lat,lng,zoom` should go to exactly where is specified, regardless of whether or not 3 markers are included.

This sets the stage for allowing users to share a link directly to what they're looking at either by:

- having a "share this map" button that generates a URL with query params in it
- auto-updating browser location using the map position when users interact with the map

This accomplishes one of the feature requests embedded #601 though there may be further steps

**Comment by ngottlieb** [comment]
@linderr https://findthemasks-feature-ma-hzptaz.herokuapp.com/

I updated the README to reflect, but you can now add either:

- `?q=Google maps search` or
- `?coords=49.7476798,-123.0911333&zoom=10`

to both the main page and embed links and it will initialize the map with that.

**Comment by linderr** [comment]
Perfect!!!! Tried: https://findthemasks-feature-ma-hzptaz.herokuapp.com/give.html?coords=49.7476798,-123.0911333&zoom=10

I see you and Daphnee :)

**Comment by linderr** [comment]
@ngottlieb may you add this to the Wiki on [Embeding](https://github.com/findthemasks/findthemasks/wiki/Embedding-%23findthemasks-donation-sites-page)?
