### ISSUE TITLE
Embedded map-link should open a new tab.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#606]
From the FTM-PPE cross-slack channel:

Zach Peery-Wolf: "was doing some front end testing and when I click on the "Made in collaboration with #findthemasks. Want to join the #findthemasks map? Need to update or remove info? Complete This Form" button it's opening into a frame where I can't scroll down to the bottom of the form to complete it. Can you get it to open a new tab?"

This would also resolve @linderr 's concern:

"Interesting, and there is no way to return to the embed map after someone hits "complete this form" https://theppedrive.com/ppe-drive-listing "

Including @awong-dev .

**Comment by 4kbt** [comment]
Relevant URL: https://getusppe.org/give/

This is working for me on my desktop screen, but apparently not for all users.

**Comment by 4kbt** [comment]
Hm. Working for me on mobile, too.   Will ask for clarification.

**Comment by 4kbt** [comment]
Error apparently happened on this config: "Firefox 75.0 (64-bit) Windows 10 Home. But I just cleared my cookies and that fixed it."

We should probably still go for the new-tab, just to be safe?

**Comment by linderr** [comment]
https://github.com/findthemasks/findthemasks/pull/571

Misses target="_blank" in ftm-add-donation-site-answer but exists in all other xx.json

**Comment by saikatbhadra** [comment]
closed as from the discussion on the PR this is no longer necessary
