### ISSUE TITLE
Stats  page: "Donation Sites by State" is actually "Donation Cities by State"

### ISSUE THREAD

**Issue by vdalal** [findthemasks/findthemasks#623]
Problem:
* Stats page: https://findthemasks.com/stats.html
* Added the per State breakdown numbers (GSheets) and the total matches the total number of cities (NOT the number of sites)

Fix required:
* Change "Donation Sites by State" to "Donation **Cities** by State"
* Specifically:  "ftm-administrative-region-donation-sites": "Donation Sites by $1:"

Relevant code at:
https://github.com/findthemasks/findthemasks/blob/master/public/i18n/en.json
https://github.com/findthemasks/findthemasks/blob/master/public/stats.js

@raindrift  @saikatbhadra

**Comment by vdalal** [comment]
If we all agree that the simplest fix is to change the display text (not any other code), I can make a change to this text field ("ftm-administrative-region-donation-sites": "Donation Sites by $1:")

@graemer

**Comment by nburt** [comment]
Ah nice catch. Can you create a new string in en.json for this? I think that one might be used elsewhere. e.g. `"ftm-stats-donation-cities-by-region": "Donation Cities by $1"`

**Comment by vdalal** [comment]
Will do. thnx for the feedback @nburt

**Comment by vdalal** [comment]
git commit en.json
[master 8be6cc4] issue #623: Added new text string.
 1 file changed, 1 insertion(+)

git commit stats.js 
[master 2d6d523] issue #623: Used the appropriate text string for "Donation cities by State" field on the stats.html page.
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by vdalal** [comment]
@nburt 
Works in my Dev env, see snip below.

[snip]

Stats
Total Donation Sites: 3897

Total Cities with Donation Sites: 1887

Donation Cities by State:

AK: 2
AL: 20
AR: 15
.
.
.
[snip]
