### ISSUE TITLE
[v2 design] Link map viewport to the list view

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#627]
## User story
As a user, when I update the map (zoom, pans, etc.) the list of donation sites is updated to reflect those in my view.

Note this change should happen in the v2 design branch (not master).

**Comment by linderr** [comment]
@sumitsekhri has designed this into UX for v2. https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=183%3A5881

He wants the whole listing (is it nested in a <div>?) to be a clickable area to center the map on the geocoordinates of the respective site.

**Comment by ngottlieb** [comment]
this feature exists already [in the UX2 branch](https://findthemasks-redesign-v-3z4ril.herokuapp.com/) thanks to @nburt though Derek pointed out an issue with it (it's slightly funky when you click on a marker) that we still need to resolve

**Comment by ngottlieb** [comment]
resolved by https://github.com/findthemasks/findthemasks/pull/607
