### ISSUE TITLE
[v2 design] Filter out locations and listings without a lat long

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#631]
If a location does not have a lat long it should not display in our map or list view (as it will be displayed incorrectly). We have a small block of time where a listing can go live without a geocode so we should either:

1. Filter out on client side
2. Filter out on server side (i.e. don't publish until we have lat long)

Probably should happen on both sides.

**Comment by crayne** [comment]
Am I missing the reason that we don't just get the geocode for a location that is missing it, rather than filtering out the location?

**Comment by nburt** [comment]
My understanding is that this is due to geocoding only happening every 5-10 minutes which means that approved locations can be missing a lat /lng for a period of time.

**Comment by saikatbhadra** [comment]
Merging in 5 minutes

**Comment by ngottlieb** [comment]
resolved by https://github.com/findthemasks/findthemasks/pull/607
