### ISSUE TITLE
Change default mapview of Canada v2!!!

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#633]
@ngottlieb me again on this!

Will close [#564](https://github.com/findthemasks/findthemasks/issues/564) now that it makes sense to indulge me.
May we set (at some point) the default for Canada to be just one zoom setting closer?

Right now default is trying to fit all of geographic Canada - we're a long country. But may we:
![image](https://user-images.githubusercontent.com/62862914/79797569-578e2100-830c-11ea-857f-38273632223b.png)

purpose: to discern more discrete clusters b/c it's a (prettier) UX :)

**Comment by ngottlieb** [comment]
looks pretty good, my only concern is that if you're on a laptop screen (or half of my giant screen), the default zoom excludes the sites east of Montreal. But if you live over there you're probably used to scrolling over there anyway hahah

https://findthemasks-change-can-js96ba.herokuapp.com/

**Comment by linderr** [comment]
Good point about screen size/dimensions! Hold on lemme get my ultrabook. it's a short and stubby

**Comment by linderr** [comment]
LGTM!!! let's gooo
