### ISSUE TITLE
V2 hangs loading location sites in Chrome

### ISSUE THREAD

**Issue by crayne** [findthemasks/findthemasks#635]
This does not happen in Safari.  It does not happen in Firefox.  In Chrome, it does not happen in a dev environment.

**Comment by nburt** [comment]
Does this happen every time for you? I don't get it in Chrome v 80.0.3987.163. Is there anything in the console?

**Comment by crayne** [comment]
It happens every time for me.  I am running Chrome v 81.0.4044.113.  In the console:
Uncaught SyntaxError: The requested module './getCountry.js' does not provide an export named 'default'

**Comment by crayne** [comment]
I think this line in getCountry.js

```
export function getCountry() {
```
should be 

```
export default function getCountry() {
```

**Comment by nburt** [comment]
hmm yeah I'm seeing that in our Airbrake logs. I wonder if this could be a caching issue? I can't seem reproduce it. I can only find named imports of getCountry in the codebase:

![image](https://user-images.githubusercontent.com/5788989/79868873-92e12c00-83ae-11ea-8e01-94155738ff50.png)

![image](https://user-images.githubusercontent.com/5788989/79868887-98d70d00-83ae-11ea-8e3b-5f8f68529754.png)

Can you let me know if you're still seeing this issue?

**Comment by crayne** [comment]
Unfortunately, yes.  I did clear the cache.  I'm mystified about the difference in behavior between dev and production.

**Comment by saikatbhadra** [comment]
Link to the airbrake issue: https://find-the-masks.airbrake.io/projects/266956/groups/2726861397683913057?tab=overview

**Comment by saikatbhadra** [comment]
@nburt I believe this is the issue: 

https://stackoverflow.com/questions/54590951/uncaught-syntaxerror-the-requested-module-add-js-does-not-provide-an-export

**Comment by crayne** [comment]
Actually I looked at the source for locations-list-map.js.  In the dev console  of findthemasks.com the import for getCountry is:

import getCountry from './getCountry.js' 

and the import for getCountry in the source of my pull from master is: 

import { getCountry } from './getCountry.js'  

so that would imply a caching problem, no?

To confirm this, if I run the dev version and look at the console, the import for getCountry in the dev console is:

 import { getCountry } from './getCountry.js';

My dev version runs correctly.

**Comment by crayne** [comment]
www.findthemasks.com.har
