### ISSUE TITLE
[v2] Partners Subpage - build and UX/UI

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#648]
This week we're going to see a lot of #comms outreach success!

4/22 - Western University feature student volunteers Amy & Betty 
4/22 - Harvard PPE Ethics panel feature Rachel & Linda
4/24 - Google Maps Blog feature

It would be very nice to show who has been sponsoring us and for all of our grassroots collaborators to benefit from the pending traffic uptick if we could surface our Partners page. 

HeatherQ's Partner's A - 6 col - [Desktop design is ready.](https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=767%3A6417)
Content: [By region (tabs)](https://docs.google.com/spreadsheets/d/1bzf_ZxWtDV_fagpOB9f8dy1yKJN1Elqy11ak2S4IuLs/edit?usp=sharing)
Logos: [Google Drive](https://drive.google.com/drive/folders/1q9ds6bca2qDi3YeJiqsDhwuI37t9Nxds?usp=sharing)

@stefanie or I on Slack if there are any questions or you require permissions. 
CC @tinabeans

**Comment by saikatbhadra** [comment]
If any devs have spare cycles it would be to just get a page out with content (even if it doesn't have the styling beauty of the design). See the volunteer and whoweare pages for examples of quick subpages.

**Comment by sikakkar** [comment]
Got this started in the partners-page branch. 
@linderr are there SVGs for the logos?

**Comment by linderr** [comment]
@sikakkar no sorry, we just hacked this :)

**Comment by linderr** [comment]
If you mean where the logos are stored: https://drive.google.com/drive/folders/1q9ds6bca2qDi3YeJiqsDhwuI37t9Nxds?usp=sharing
