### ISSUE TITLE
embed page (give.html) should have logo or our name in the top part

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#652]
We should have a logo of find the masks at the very top of the embed to ensure that donation site requestors always know where to do a takedown request. Right now the only mention is below the map which can be cut off by iframes. Embedding in the map would be a cool trick too.

**Comment by linderr** [comment]
@tinabeans @sumitsekhri thoughts?

**Comment by saikatbhadra** [comment]
I'll defer to UI here, but I think this important for healthcare workers who submit their sites from an embed page to takedown or update (that's the main use case here).

**Comment by saikatbhadra** [comment]
Closing this as we have a v2 design now
