### ISSUE TITLE
findthemasks.com/whoweare.html should credit airbrake

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#653]
Please thank airbrake for giving a sponsored account to catch Javascript errors.

**Comment by linderr** [comment]
Added to Partners spreadsheet just need a dev now :)

**Comment by linderr** [comment]
All sponsors are now on the live www.findthemasks.com/partners page!

**Comment by saikatbhadra** [comment]
It's not a big deal but I think we are still missing airbrake so keeping this open

**Comment by linderr** [comment]
Yes, please keep it --- sorry I am working on my final project for school. I'm presenting next Tuesday!
This is on my To do. I'll close it when I add it to the Partner's list and get a dev to update :)

**Comment by nburt** [comment]
Closing, looks like this was done
