### ISSUE TITLE
Do not link new FTM2 page yet

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#658]
See Albert’s 12:04a post on #general. 

Please do not link from main page yet. Need lots of content edits, UX/UI designs and partners need to update data for this adaptation, thanks!!

**Comment by saikatbhadra** [comment]
The won't label means that the team has decided not to do the work proposed in a github issue so don't put that label on :).

What is FTM2?

**Comment by saikatbhadra** [comment]
Can we close this?

**Comment by linderr** [comment]
@saikatbhadra yes!
