### ISSUE TITLE
[v2] Apply UX/UI on FAQ page

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#664]
FAQ skeleton + content is up.

Just needs final touches as per 'dev ready' version on Figma :)

**Comment by saikatbhadra** [comment]
Can you link to the figma in case someone doesn't have the link? Thanks!

**Comment by ngottlieb** [comment]
available for review here: https://findthemasks-feature-fa-ivus8z.herokuapp.com/faq
