### ISSUE TITLE
[v2] Apply UX/UI on Join Us page

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#665]
Skeleton and content are up but it's called "volunteer".

Please apply UX/UI design to this :)

**Comment by saikatbhadra** [comment]
Can you link to the figma in case someone doesn't have the link? Thanks!

**Comment by stefmvr** [comment]
https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=767%3A6417

**Comment by ngottlieb** [comment]
@linderr I have a question about the "Join Us" page. The Figma has a two column layout with a sort of even amount of text on both...but in the Google doc, the text that would go in the left column is very short by comparison. So the columns won't look even or good when split that way...

Am I missing something? Or do we need to reconsider the design a little bit given the content? If the content is correct, I think it should be a single column layout (as it is in the status quo).

**Comment by ngottlieb** [comment]
Another question: the existing Volunteer page has no translations. I think this has been discussed in the past -- we can't really accept help from people who don't speak English, at least to some degree -- so is it OK to leave it untranslated with the new design?

**Comment by linderr** [comment]
@ngottlieb i'm going to ask on #i18n and #languages
I personally see the utility of leaving it English but am obviously biased as a native EN speaker. I think it could be good UX/UI etiquette to at least put in a 1-liner preamble statement to explain why when someone selects Germany + German in the top header, showing English subpages isn't a bug but a ____choice?___
