### ISSUE TITLE
English version of France site Form links to FR-FR Form

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#676]
When viewing FTM-France, the English button should go to France-EN form?
It links to FR-FR now.

**Comment by saikatbhadra** [comment]
i've tested on a couple browsers and devices and even from a japanese vpn so I don't think this a cross user issue, not sure what the problem is but it could be:

1) caching issue
2) some oddly specific issue on the logic for donation-form-bounce

**Comment by saikatbhadra** [comment]
I don't believe we have an english form for France so I believe this is not a bug. Intended behavior is to fallback to FR-FR

**Comment by nburt** [comment]
Correct, we do not have a France-EN form

**Comment by linderr** [comment]
@nburt @saikatbhadra 
Then what is being listed here: https://github.com/findthemasks/findthemasks/wiki/International-Forms-and-Data

**Comment by linderr** [comment]
Specifically this form (let me know if you need access): https://docs.google.com/forms/d/1nyejh2JL0YtOkMw87UtMDKXY8oVcJQnfEyusGjNVpmA/edit?usp=drive_open

**Comment by linderr** [comment]
I had gone back through all the forms a few weeks ago to set permissions on all of them and remember we had a FR-EN. Just not in-charge of it and thought it was a bug we linked to the wrong language form for France when viewing on English

**Comment by linderr** [comment]
@nburt this FR-EN is linked to the combined Google Sheet. 
You guys have set up both EN and FR raw data to output there from Form.

**Comment by linderr** [comment]
Let me know! Happy to test :)
