### ISSUE TITLE
Fix hrefs for crawlers in top_nav

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#681]
I think this point was brought up in slack earlier for the whoweare page but this isn't great for crawlers. Fix all the <a> in the top nav so the href is set correctly with i18n parameters

_Originally posted by @nburt in https://github.com/findthemasks/findthemasks/pull/673_

**Comment by nburt** [comment]
Closed by: https://github.com/findthemasks/findthemasks/pull/834
