### ISSUE TITLE
[ui/ux] Restyle about page (whoweare) to the new design

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#684]
Designs are here: 
https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=767%3A6417

**Comment by sikakkar** [comment]
Just styling or content too? It's Totally different in the figma design

**Comment by saikatbhadra** [comment]
Let me send you the content link if you'd like to do the content updates. Or if you just want to do styling, you can fill out with fake text and I can close out that part
