### ISSUE TITLE
Settle on a plan for entry expiration or refresh

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#688]
How will we expire entries?  We need to pick an age. It'll be painful, because we picked up about a thousand entries in the first few days.

Sending out a refresh email may need to wait for the mail relay, or at least a firm plan for the mail relay. so we can message that correctly in the updating form.

**Comment by linderr** [comment]
I appreciate these considerations, @4kbt !!

**Comment by saikatbhadra** [comment]
Why do we need to wait on mail relay? Can we just test out the feature by sending a batch of templated emails from our email domain? It will give us an idea of % of responses, bounces, etc.

**Comment by 4kbt** [comment]
It isn't essential -- just that we could get a lot more public
email-contacts going if we could promise that recipients wouldn't have
their emails listed in public.

It's going to be a big data-moderation job when we send that thing, as
suddenly essentially every entry will have a duplicate.

**Comment by 4kbt** [comment]
The refresh process has begun. The plan isn't settled, but #755 is the natural continuation of this ill-defined bug.
