### ISSUE TITLE
[bug] Facility type dropdown missing

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#694]
index and give used to have a facility type dropdown so you could filter by facility type. That seems to be missing currently, which I believe is a bug.

![Screen Shot 2020-04-24 at 9 45 26 AM](https://user-images.githubusercontent.com/2250961/80236885-a68bcd00-8610-11ea-872a-cf49bc813f17.png)
![Screen Shot 2020-04-24 at 9 45 16 AM](https://user-images.githubusercontent.com/2250961/80236888-a7bcfa00-8610-11ea-8504-5fbc97659dac.png)

In case this is a user specific bug
Browsers: tested on chrome and firefox

**Comment by linderr** [comment]
CC @tinabeans please check the design of the fix!

**Comment by ngottlieb** [comment]
@linderr the design of the fix is identical to how it was before it disappeared (it didn't actually get removed and added, the parsing of organization type from our dataset got broken)

**Comment by linderr** [comment]
Perfect!!! @ngottlieb
