### ISSUE TITLE
www.findthemasks.ca directs to US-site

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#698]
www.findthemasks.ca should redirect to www.findthemasks.com/ca :) 
***map view + wrong side of the border is dimmed***

**Comment by ngottlieb** [comment]
I can't replicate...

**Comment by ngottlieb** [comment]
OHHH I see. It does redirect to `www.findthemasks.com/ca` but it's still showing US sites despite having the right URL!

**Comment by linderr** [comment]
On Chrome: Map loads US -centre with US pins highlighed x Canada dimmed

**Comment by ngottlieb** [comment]
yes, the problem is that even if you go directly to https://findthemasks.com/ca it's showing US sites. It only matches https://findthemasks.com/ca/ (with a trailing slash)

**Comment by ngottlieb** [comment]
same for other countries (obviously)

**Comment by linderr** [comment]
lol. Is that the default? oi

**Comment by linderr** [comment]
btw I really appreciate this education - it makes sense why it didn't work
(but why does it work like that.................)

**Comment by ngottlieb** [comment]
it's a bug for sure, just a tricksy one

**Comment by linderr** [comment]
Cannot change www.findthemasks.ca ---> www.findthemasks.com/ca**/** ?

**Comment by ngottlieb** [comment]
well, we could do that, but it also should just work to do www.findthemasks.com/ca in my opinion

**Comment by linderr** [comment]
I agree :) thanks for fixing!!! I see it’s fixed for all international /fr /gb etc. Closing
