### ISSUE TITLE
Tracking or credit for donors

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#7]
Idea that was emailed in: If there is a way to track and share who donated, that might be good incentive for people to donate.  I've been working with local dental societies to ask dentists to donate PPE.  But dentists are struggling now, some laying off employees, and PPE is valuable.  Some free marketing for people who donate might help them!

**Comment by vdalal** [comment]
Would we need the donors permission to publicize this information?

QUICK
1. Tweet (or FB) from our @findthemasks account?
2. Widget on the top RHS of our page showing the details
3. Donations are almost always local (& donor would like to be acked in the community) so am 
     going for that vibe in our tweet (post)
4. If donor opts out, we can anonymize the post with (say)
  -- "A neighbor in #SantaClaraCounty, donated 100 N95 masks and 10 gowns 
       to PAMF, #Sunnyvale, CA. Thank you. #PPE #GETUSPPE" OR 
 - if the list of donated items is long
  -- "A neighbor in #SantaClaraCounty, donated 100 N95 masks, 10 gowns, 100 protective shields 
       & other #PPE equipment to PAMF, #Fremont, CA. Thank you. #PPE"
5. If donor, opts in:
  -- "Bright Smiles Dental, #Fremont, CA, donated ..... Thank you. #PPE #GETUSPPE"

LONGER TERM
1. Accessible via the Footer (or Header?)
* With the details of donation:
  -- from: per person or business
  -- to
  -- day/date
  -- item(s)
  -- Qty
  -- other

**Comment by saikatbhadra** [comment]
going to close this if no one has any objections
