### ISSUE TITLE
Contact Card has information and UX/UI missing! [Regression]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#731]
The Contact Cards don't have any information on whether open boxes are accepted or not. This is very important information. Not sure when it got lost, it was on the Contact Card previously with V2.0 last week  

![image](https://user-images.githubusercontent.com/62862914/80394263-79d0f300-8866-11ea-8f86-ecb67f98573c.png)

Check final DEV READY designs here for desktop: https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=183%3A5881

**Comment by ngottlieb** [comment]
I believe this is another victim of linting efforts changing `open_box` to `openBox`, it's probably been this way for almost a week. will confirm that's the issue and test

**Comment by ngottlieb** [comment]
@linderr https://findthemasks-bug-open-b-bbjonp.herokuapp.com/

**Comment by ngottlieb** [comment]
(actually discovered a second related issue: on the marker clumping, markers other than the first one wouldn't show organization type either. fixed that too)

**Comment by linderr** [comment]
Thanks @ngottlieb !
