### ISSUE TITLE
Allegro Pediatrics rows are evergreen in Form Responses 1 (Google Sheet)

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#74]
The Allegro Pediatrics entries (timestamped March 20) at the bottom of the Form Responses sheet are perpetually at the bottom. Newly-submitted entries from the form appear above them.

It doesn't block functionality at all, but the behavior is unexpected.

**Comment by r-pop** [comment]
My guess is that these entries were added directly onto form response 1 instead of through the form. If so, we could probably fix by removing these rows and plugging them through the form... but i'm always hesitant to do stuff like that on google forms.

@skimekerr is that what happened?

**Comment by cchang-adi** [comment]
@4kbt valiantly re-entered every Allegro Pedatrics location into the form so that there are entries for Allegro that no longer keep going down. I think we can probably safely delete the buggy rows but am holding off on that.

**Comment by 4kbt** [comment]
Agreed -- now may be a good time to remove those rows, especially if there is any attempt to copy-paste/munge the PPELink rows directly into the findthemasks Sheet.

**Comment by awong-dev** [comment]
removed now.
