### ISSUE TITLE
Add ability to link to an FAQ with id hash and have it default open

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#740]
As part of updating contact email formatting we want to link to a specific FAQ section from the email footer similar to how craigslist does it: https://github.com/findthemasks/findthemasks/issues/723

For that to work we need the ability to link to a specific question / answer. I think this could be useful elsewhere

**Comment by linderr** [comment]
Makers want this as well to jump straight to the Makers FAQ section

**Comment by saikatbhadra** [comment]
You can link to any element of the faq that has id tag associated with it. You can check it out by trying out this link: https://findthemasks.com/faq#ftm-faq-how-to-help
