### ISSUE TITLE
[change destination URL] FAQ on FTM-CA site links to US-FAQ

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#745]
FAQ menu on top header of www.findthemasks.com/ca goes to www.findthemasks.com/faq
Should go to www.findthemasks.com/ca/faq

Contains Canada-specific information particularly for 500+ item donations which should go to provincial and national government. GetUsPPE does not exist in Canada.

**Comment by ngottlieb** [comment]
what browser are you on? That doesn't happen for me.

**Comment by ngottlieb** [comment]
(it goes to /ca/faq when clicking the menu link from any page, for me)

**Comment by ngottlieb** [comment]
Ah, I get it. This is another manifestation of the `/ca` vs `/ca/` bugs we've been seing, it's nothing to do with the Faq link in particular.

(It works fine if you are on `/ca/` instead of `/ca`)

**Comment by linderr** [comment]
I see. So the issue then is:
1. we link people to www.findthemasks.ca (this domain makes more sense for Canada)
2. this refreshes to www.findthemasks.com/ca (no trailing slash)
3. clicking FAQ on the menu will bring them to American FAQ content.

This must be so annoying for you guys with the / x / thing!! wow
