### ISSUE TITLE
Available donation sites not appearing

### ISSUE THREAD

**Issue by tacosen** [findthemasks/findthemasks#75]
When I got to the site and scroll down to see the hospital/donation site locations, none appear.

Browser: Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)
OS: MacOS Mojave Version 10.14.6

![Screen Shot 2020-03-21 at 6 32 36 PM](https://user-images.githubusercontent.com/62488779/77239289-73889080-6baf-11ea-85bd-48a3ff19fb5c.png)

**Comment by cjimmy** [comment]
@tacosen is this on the public website or on a locally run server? If locally run, you'll need to download https://findthemasks.com/data.json and store it locally. I'm not sure why it's not in the repo. @r-pop – any reason why `data.json` is not in the repo?

**Comment by r-pop** [comment]
it is automatically generated and placed on the server by a crontab.

The dev chat is trying to solve this issue (Jimmy - we're on fb, please add me (/rachelpopkin) and i'll drop you in there if you want.

**Comment by r-pop** [comment]
We think this is fixed. If anyone sees it again, please comment.

**Comment by shahronak** [comment]
I tried it on mobile iOS Safari and am still hitting the issue. Cleared my website data cache and tried again.

**Comment by liamrosen** [comment]
Still broken on Firefox and Chrome.

**Comment by r-pop** [comment]
Got a report from IE and Chrome today, same behavior Chrome incognito. Windows, enterprise-enrolled device. "I noticed that the list of donation locations is not showing up on my desktop (I tried IE and Chrome). It shows up just fine on my phone; not sure if it has something to do with my work laptop's settings or if this is a known issue."
