### ISSUE TITLE
[Quick - dev ready] Add Nation of Makers logo/link to US collaborator subheader on Partners subpage

### ISSUE THREAD

**Issue by cchang-adi** [findthemasks/findthemasks#752]
We’ve launched findthemasks.com/makers, and we’d like to acknowledge our maker data partners at Nation of Makers on the US partnerships page. https://www.nationofmakers.us/

Dorothy Jones-Davis and Claire Cocciole are our main contacts there if you need more info, high resolution logos, etc.

**Comment by kocsioli** [comment]
Hi. Can you use a png file? If so, here is the Nation of Makers logo. 
![NationofMakers](https://user-images.githubusercontent.com/63983558/80599314-bd5b6680-89f8-11ea-82a1-a8a7e0f8dcd7.png)

**Comment by linderr** [comment]
Yes we can!

**Comment by linderr** [comment]
I added Nation of Makers to our Dev Ready spreadsheet: https://docs.google.com/spreadsheets/d/1bzf_ZxWtDV_fagpOB9f8dy1yKJN1Elqy11ak2S4IuLs/edit?usp=sharing

**Comment by linderr** [comment]
Devs please add row 13's logo and URL to the "Collaborators - US" subheader on /partners - thank you!!
