### ISSUE TITLE
UK data not pulling through to webpage 

### ISSUE THREAD

**Issue by DrewHuntdh** [findthemasks/findthemasks#754]
First time using GitHub so sorry for the non-technical terms. Essentially, we aren't getting the data from the UK googlesheet (https://docs.google.com/spreadsheets/d/1qPUdGOEZl-c8sQ6Vlm7h48OZScBOVGjzz88AyGCQvEc/edit?ts=5ea34673#gid=1161906733) across to the website. When I run https://us-central1-findthemasks-dev.cloudfunctions.net/reloadsheetdata/uk I can see the new/amended data- but it doesn't seem to go onto the site. Can someone please help?

**Comment by nburt** [comment]
Above is the dev url, sent Drew the production one in slack, closing
