### ISSUE TITLE
Homemade Masks shows up twice in filter list?

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#768]
<img width="676" alt="Screen Shot 2020-04-30 at 12 15 11 AM" src="https://user-images.githubusercontent.com/144579/80682582-aad44200-8a77-11ea-92c8-253add20a118.png">

**Comment by nburt** [comment]
For whoever picks this up, something is wrong with formEnumLookups.js. Something here I think...

![image](https://user-images.githubusercontent.com/5788989/80720175-8ce3fd00-8aca-11ea-8249-e49ace548d73.png)
