### ISSUE TITLE
Build a prototype refresh-email mail-merge

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#770]
The current template is below the line.  We have begun manually mail-merging in order to send test messages, but the process is slow and inconsistent (~2 minutes/email, ~3,000 emails needed, easy to make mistakes).

The fields we need to fill (negotiable, if needed):
0. Email address :).
1. Row number in the subject
2. INTAKEDATE: Day that they filled in the form (Date from Timestamp column)
3. CARDINFO: Contents of the map-card
4. LINK: A geocoded link that shows where they are on the map  (https://findthemasks.com/?q=42.2642694,-71.8021422 seems to work, just including Lat and Long with a comma between)
5. EXPDATE: The date on which their entry will expire (7 days from the first-sending date).

--------------------------------------------------------------

From: data@findthemasks.com
Subject: Please update your PPE information at FindTheMasks [FTM #]
To: EMAIL_ADDRESS 
cc: data@findthemasks.com

Hello from FindTheMasks!

On INTAKEDATE, you, or someone referencing this email address, filled in a FindTheMasks or GetUsPPE form to list a location for PPE donation on our public map at https://findthemasks.com.
In a few days, we will begin expiring entries in our registry that are more than 21 days old. **Your entry will expire on EXPDATE. **

**PLEASE UPDATE OR REMOVE YOUR ENTRY HERE:
https://findthemasks.com/us/donation-form**

Please update your entry so that community donations, mask-and-PPE makers, and public-health organizations can help you stay safe as you care for others. If you no longer need donations of PPE, please select "Remove an existing donation site" and answer the questions at the bottom of the form.

Your public listing:

CARDINFO

Map Link:
LINK

Do you know of healthcare workers or institutions that are experiencing PPE shortages? Please share #findthemasks with them. We won't stop until everyone has what they need.

Keep fighting the good fight -- we are doing everything we can to help you!

Catherine and Charlie, Data-Leads at FindTheMasks

**Comment by cchang-adi** [comment]
We may be able to qualify for a free charity account with MailChimp: https://mailchimp.com/covid19-public-service-support/

"To be eligible, organizations must have 10,000 contacts or fewer across their audiences, and be sending urgent information about changes to hours, processes, or guidelines; city or state-level ordinances and other urgent updates for citizens and residents; and/or information about how to access relief services, such as food pick-up or other kinds of urgent assistance."

I believe we count as urgent assistance, and we have fewer than 10k contacts right now.

**Comment by 4kbt** [comment]
I'm looking at their design guidelines now -- useful indeed.

**Comment by 4kbt** [comment]
Prototype works, tested. First outbound batch of 194 emails is scheduled for 8:30 AM Pacific on Monday.
