### ISSUE TITLE
Identify usable emails from the first 1500 entries

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#772]
Our first 1500 entries were acquired without email addresses. In order to ask those recipients to give us an update, we need to know their emails.

@cchang-adi has a line on some of those emails from an old spreadsheet of Ethan's.

**Comment by cchang-adi** [comment]
I have the link to the old spreadsheet and can add other users who need access to it.

**Comment by cchang-adi** [comment]
I'm creating a separate spreadsheet with the mails from Ethan's sheet.

**Comment by cchang-adi** [comment]
Also, many hospitals have their COVID-19 response sites up, and many of these will have donation info and instructions including a contact email.

**Comment by 4kbt** [comment]
True!

**Comment by cchang-adi** [comment]
I've extracted about 100 emails from the first 1500 rows, and filled in a few from official sites. It's a little disappointing, but it's better than nothing. 

In an imaginary world where I have infinite free time, I would go Google each location to see if they have an official site up, but ...

**Comment by 4kbt** [comment]
Closing this for now? I think you more than satisfied the original ask!
