### ISSUE TITLE
Wire up continuous expiration/refresh-email merge/send.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#775]
Blocked by #774 

Once the refresh-emails are working smoothly, and the backlog has begun to be addressed, we will want to do this daily at ~9 AM Eastern:

1) Send first-refresh emails to any approved entries that are more than 14-days old that haven't yet gotten a first-refresh email.

2) Send second-refresh email to any approved entry that hasn't yet gotten a second-refresh email if it has been more than 6 days since the first-refresh was sent.

3) Un-approve any approved entry that has had more than two days since the second-refresh email was sent. Mark "Reason for removal" with an "X" for expired.

4) Reloadsheetdata.

**Comment by cchang-adi** [comment]
Could #1 and #2 be solved with MailChimp?

**Comment by 4kbt** [comment]
Don't know yet -- for continuous operation, I don't know how much logic from MC can integrate with the Sheets.   I'm a little bit wedded to the idea that the Sheet is the source of all truth, which would mean that MC would need to be able to read from the sheet that the email had not yet been sent and write back to the Sheet that the emails had been sent.

I'm sure something like this exists somewhere, though :).

**Comment by cchang-adi** [comment]
So it seems like Zapier could solve this problem for us, with dynamic
updates of the contact list ("Audience") as well. I think Jenni N is using
Zapier already for something involving her Airtable.

https://zapier.com/apps/google-sheets/integrations/mailchimp/5/add-subscribers-to-mailchimp-from-a-google-sheets-spreadsheet

**Comment by linderr** [comment]
@4kbt I think you solved this by Mail Chimp?
Looking forward to learning!
