### ISSUE TITLE
 Add Sheets dashboard entry to assess the number of entries that are 7, 14, 21, and 28-days stale.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#777]
As we embark on the data-refresh email campaign, it will be useful to have quantitative measures of how stale our entries are.

The dashboard tab in the Sheet seems like the right place to do it (though it could also be computed straight out of data.json). 

It seems like 7, 14, 21, and 28 days are roughly the right tiers for the numbers, as they're "okay, soon, old, ancient"

**Comment by linderr** [comment]
Hey @4kbt do we still need this functionality? Or are we happy with the public display of "Last Updated"?

**Comment by 4kbt** [comment]
The new filters and entry_age column essentially solve this problem.
