### ISSUE TITLE
Crosslink makers (Findthemakers.com, findthemasks.com/makers) and findthemasks.com

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#782]
We should figure out how to cross-link between findthemakers.com (as well as findthemasks.com/makers) and findthemasks.com/.

We should think through branding and conversions and how to support the full maker/requester product ecosystem.

For examples, makers will know their local institutions that should register themselves as wanting good and can help get them to sign up.

Institutions will want to know their local makers to request goods from.

How to do that?

But priority #1 is cross-linking.

**Comment by awong-dev** [comment]
@dhruv4

**Comment by pratapjayaram** [comment]
Link to dev ready designs: https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=1272%3A9032
