### ISSUE TITLE
[Quick] Add AirTable to Sponsor logo list on Partners subpage

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#783]
Logo: https://drive.google.com/drive/folders/1CGturZ-1VIUT7Wor2Gjq8iszKd6iz9uq
URL: www.airtable.com

Our entire Makers map is supported by their gift of a Pro Account to us from a fancy Intake Form to data mod single handedly by Claire C. (and amazing lady) of Nation of Makers.

AirTable is going to do some free press for us so we should list them on our Partner page ASAP

**Comment by linderr** [comment]
@ywyw are you able to help with these requests?

**Comment by ywyw** [comment]
@linderr yeah I can take this one!

**Comment by linderr** [comment]
@ywyw sorry I can trying to learn lol
