### ISSUE TITLE
Maker Page - the left logo does not link back to Find the Masks main page

### ISSUE THREAD

**Issue by dottiemaej** [findthemasks/findthemasks#793]
On www.findthemasks.com/makers - the left logo does not link back to the FTM main page

**Comment by nburt** [comment]
should this just redirect to findthemakers.com instead?

**Comment by dottiemaej** [comment]
Wouldn't we want it to redirect to Find the Masks? 

Use case: Maker finds makerspace and then wants to find facility to accept fabricated PPE - how do they get back to the main page without opening a new tab/window and navigating to it?

With that said, maybe there is already another way to get back to the main FTM page?

**Comment by nburt** [comment]
I'm thinking that `findthemasks.com/makers` should redirect to -> `findthemakers.com` now that that domain is setup. Then there's a button in the top left to go back to findthemasks, does that sound right?

![image](https://user-images.githubusercontent.com/5788989/80876920-3113a280-8c89-11ea-8d41-aef4986fcd43.png)

**Comment by dottiemaej** [comment]
Perfect. Also, when I was thinking about this, I didn't realize there was a big yellow FTM button there on the right, lol! I'll close this issue.
