### ISSUE TITLE
Autosuggest google maps API broken

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#795]
Tested on mobile safari and desktop chrome. Looks related to API/billing issue
![Screen Shot 2020-05-01 at 2 09 08 PM](https://user-images.githubusercontent.com/2250961/80841991-6353d000-8bb5-11ea-9712-ca8cd278895a.png)

**Comment by awong-dev** [comment]
I *think* I fixed this.  We moved the maps API key from @susanashlock 's account to the findthemasks one and I don't think I correctly migrated all the enabled APIs.

It started working for me a few minutes ago. Hopefully it'll get fixed everywhere soon.

**Comment by awong-dev** [comment]
leaving until verified.

**Comment by nburt** [comment]
working for me!
