### ISSUE TITLE
Update About Us subpage: content + UX/UI

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#801]
**Design only** as per two-column "About-Desktop" frame on Figma: https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=287%3A4547

**Latest Content** page 9-12
https://docs.google.com/document/d/1b9lj2j3vqJrZgqfozbZ2reSO6xnC_a00VtKO-xxUB7g/edit#
- text sections indicated which should go on the right column 
- right column is region-specific

![image](https://user-images.githubusercontent.com/62862914/80853035-63b69000-8be2-11ea-9528-5b04a26b39ff.png)

**Comment by ngottlieb** [comment]
@linderr https://findthemasks-feature-ux-bpcxgf.herokuapp.com/whoweare

**Comment by linderr** [comment]
@ngottlieb this is sooooooooo much better!
