### ISSUE TITLE
Update Makerspace FAQ text [new FAQ question]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#802]
New content to reflect partnership with Nation of Makers (page 5-6) " Who are #findthemasks Makers partners?":
https://docs.google.com/document/d/1b9lj2j3vqJrZgqfozbZ2reSO6xnC_a00VtKO-xxUB7g/edit?usp=sharing

**Comment by nburt** [comment]
closed via https://github.com/findthemasks/findthemasks/pull/808
