### ISSUE TITLE
Fix mobile display of Partners page using UI mockup

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#806]
Partner page looks awful on mobile: 
![1823EC13-565E-4608-85C9-CFC070D77EF5](https://user-images.githubusercontent.com/62862914/80859823-721f9e80-8c18-11ea-8d35-ef12de68cb70.png)
iPhone 7 - partner logos are microscopic. 

See UI mockup on Figma for suggested mobile version of Partners page:  https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=767%3A6417
- sponsors: single-column logo stack 
- media&collaborators: two-column logo stacks

**Comment by nburt** [comment]
https://github.com/findthemasks/findthemasks/pull/810
