### ISSUE TITLE
Encourage form submitters to link to the recipient's own instructions

### ISSUE THREAD

**Issue by mx00s** [findthemasks/findthemasks#81]
Recently I learned about [Seattle Children's request for donations](https://m.facebook.com/story.php?story_fbid=10157320680637061&id=14517117060) from a local nurse. I know they've edited that post at least two times, slightly revising what they are willing to accept and drop-off location options. It would be great if this URL was linked under Seattle Children's so everyone could verify the latest information with minimal communication overhead.

More generally, encouraging form submissions to include links like this could help keep all the information current. The field for

> Drop off instructions, eg curbside procedure or mailing address ATTN: instructions:

could include something like this:

> (recommended: link to their public request where information is kept updated)

**Comment by mx00s** [comment]
By the way, Seattle Children's isn't currently accepting any kind of N95s. Their post currently says

> Update: We are currently accepting basic isolation masks and surgical masks. At this time, we kindly decline any other masks. We currently do not have a need for anything other than masks (e.g. latex gloves) at this time.

They [clarified for me](https://twitter.com/seattlechildren/status/1240749605807165443) what they mean by "basic isolation masks".

**Comment by r-pop** [comment]
Could you submit a new entry for Seattle children's through the form that has the updated info and the link? from there we can publish and remove the older entry.

I can't change the form field titles, because it breaks our pipeline (which I learned the hard way earlier today!) If it becomes worthwhile to update this to add the things you've requested, we'll need to have a brief downtime to do so. Right now I don't think it's worth it.

**Comment by cchang-adi** [comment]
I submitted a new entry for Seattle Children's and a separate one for the Bellevue clinic mentioned in the FB post. Added new instructions, link, and removed N95's.

**Comment by tinabeans** [comment]
Hello! Right now the text on the form says "Drop off instructions, eg curbside procedure or mailing address. If you want donors to email or call you, please include contact info that can be made public in this field:" 

What if we changed it to: "Write drop off instructions below or paste a link to your organization's own page containing instructions. For written instructions, please include details such as curbside procedure, mailing address, email address, and/or phone number. Please note all information entered here will be made public." (Slightly copy-edited for clarity)

**Comment by mx00s** [comment]
See the 2nd paragraph of @r-pop's reply. Unless the technical barriers have been remedied this may not be feasible.

**Comment by r-pop** [comment]
Yes, we now have separated the human-readable label from the code-readable labels in the sheet. Big relief. I like Tina's edit and will make it on the US-en form now.

**Comment by r-pop** [comment]
Fixed!
