### ISSUE TITLE
Change Mouse hover on top-left Logo from Select to Hand [FTM & Makers]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#827]
Users need a clear way to navigate back to the main map from subpages. Currently that is not clear on both FTM and FTMakers.

**Context**
When you are on a Subpage and want/need to navigate back to the map, the UX is to click on the top-left logo to go back to the map.

Right now, the mouse hover is a Select Tool (capital I-looking thing) which does not clearly indicate the top-left logo is clickable. Also the logo text becomes grey upon hover, further confusing whether the logo is clickable or not.

**Asks:**
- change the mouse hover over the logo from Select to Hand on both findthemasks.com and findthemakers.com
- change the hover text to be not-grey

**Comment by ngottlieb** [comment]
actually, clicking the logo doesn't even do it! You have to click the text "Findthemasks" right now. I'll make the whole thing clickable.

I'm not sure about the logo text becoming gray, I don't see that behaviour. What browser @linderr? it may have changed since you created the issue.

**Comment by nburt** [comment]
I fixed the "going gray" part with the navbar rewrite so I think the new scope is just making the logo clickable

**Comment by linderr** [comment]
Lol! Great catch @ngottlieb & thanks for doing that @nburt - looks like we’ll close this one pretty quick. Thank you, guys!!
