### ISSUE TITLE
Make country-specific navigator work for findthemakers.com

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#828]
Spinning wheel of death on findthemakers.com when you try to navigate to any other country than the US
https://findthemakers.com/ca/makers/

URLs are broken cause the site structure expects a different data file per country but that's not how the makers are setup. - Albert

Please show us the same map regardless of country 😄

**Comment by r-pop** [comment]
Desired behavior: users from all countries can see a global makers map

It's important that we don't expose and dead ends - no spinny cursor of death - but up to devs whether temporarily hiding the country selector is the right hotfix or if you want to fix a different way.

**Comment by r-pop** [comment]
Also let's hide the language selector since it doesn't work.

**Comment by nburt** [comment]
A few of the strings aren't properly marked up for translation, created a separate issue to just fix that since it'll be simpler than hiding the selector: https://github.com/findthemasks/findthemasks/issues/836

**Comment by awong-dev** [comment]
Fixed by #906
