### ISSUE TITLE
FAQ - Update for India 

### ISSUE THREAD

**Issue by gauravguptak** [findthemasks/findthemasks#839]
![image](https://user-images.githubusercontent.com/44533055/80945178-13852c80-8da0-11ea-8b07-5d10f491e6f7.png)

The partner link should be in.getusppe.org/give

**Comment by linderr** [comment]
@gauravguptak Sorry, I thought this could be achieved through a link and text change but the devs need to create a partial large_donation_sites.handlebars file for India's FAQ to fix this

**Comment by saikatbhadra** [comment]
Was just fixing this @linderr
