### ISSUE TITLE
Expose timestamp in list/map view

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#843]
As our dataset ages, our listings span more than six weeks of time. While we are working on refreshing as many entries as we can, we would like to let donors know how recently an entry was last updated.  By surfacing this information, we may not need to expire entries off the list as quickly.

A timestamp field is already in data.json. We could expose it to donors as "Last Updated: ".

This is in service of adding a filter to allow donors/makers to select an age range to view.

**Comment by linderr** [comment]
Are you envisioning an actual time/date stamp (which might be on the side of too much information)?
Or "this week!" "last week" "2 weeks ago" etc?

**Comment by 4kbt** [comment]
I'd imagined the date/timestamp. It'd be pretty to strip the time and leave
just the date, but printing the existing value in data.json is the minimum
step needed to get the feature added.

**Comment by nburt** [comment]
I'd vote for just a simple date format like MM/DD/YYYY (format localized by locale / country). We can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat for intl formatting.

**Comment by saikatbhadra** [comment]
Just merged, feel free to test it out
