### ISSUE TITLE
Headers and columns misaligned in CSV output

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#849]
We just got this from a consumer of our raw output data: 

"We noticed yesterday that it seemed like there was an issue with the data feed; it looks like some of the columns are off. it looks like a new column of data was inserted to the left of "Lat", but it doesn't seem to have a column header, so the rows of csv data all have an additional right-most column that doesn't have a header and the Lat, Long, RDI, Row columns don't seem to have the correct data lining up to them. "

My guess is that there's a quick fix for this one.

**Comment by nburt** [comment]
@4kbt just merged a fix for this: https://github.com/findthemasks/findthemasks/pull/853

Can you reach out to them and let them know?

**Comment by 4kbt** [comment]
Will do!
