### ISSUE TITLE
Add ability to filter makers map

### ISSUE THREAD

**Issue by nburt** [findthemasks/findthemasks#855]
Part of this ticket will be to generalize how we apply filters between different datasets (makers vs. masks)

This will be useful as we try and add layers on top of our existing maps

Needs spec on what the filters should be, maybe capabilities though?

**Comment by linderr** [comment]
Have a call with Claire later today - will ask her to confirm. Added this to M3, we should have the answers by EOD :)

**Comment by linderr** [comment]
What filters can be v1 (in descending order of most to least data entries):
- **makerspaces** (gear icon) 
- **coordinators** (truck icon) --- groups who coordinate various maker functions: delivery, centralization supply
- **manufacturer** (factory icon) --- large-scale manufacturers who have re-tooled assembly lines to pivot into making non-medical grade PPE
- **other** (x) --- catch all for every other subgroup type
- **individual makers** (x) --- people who work solo, not with a makerspace or group 

(x) indicates lack of icon preference/not selected, needs UX/UI design. Use place holder for now (icon choices do not bulk of block dev magic 😄)

**Comment by nburt** [comment]
These filters don't quite seem align with airtable group types:

![image](https://user-images.githubusercontent.com/5788989/81628665-44341a00-93cf-11ea-8cd1-f3052168f387.png)

Can you help me understand which one maps to which? Or is this a different field?

**Comment by linderr** [comment]
Yes, exactly. They have consolidated the Group Types which they'd like to keep both internally and display on the card via v2 and/or your badge idea (pushing for this week b/c I agree the length of these "types" are unruly!) Legend:
producing makerspace => **Makerspace**
coordination efforts of => **Coordinator**
producing in one space and coordinating => **Makerspace**
manufacturer retooled => **Manufacturer**
Collection site for supplier => **Coordinator**
Collection site for finished => **Coordinator**
Direct match & distribution => **Coordinator**
Community coordinator across regions => **Coordinator**
Other = **Other**

Bold is icon category

**Comment by linderr** [comment]
Closed by the awesome #923
