### ISSUE TITLE
A "Looks Good" link for our refresh-emails

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#856]
@linderr has a good idea for a way to improve our information-gathering from our refresh-emails. 

At the moment, we ask them to fill in the entire form in order to update us. While this gives us better insight into their changing needs, it takes a lot of time.

What would we need to do in order to surface a link that could make the "LGTM" button make an addition to the Sheet?  It should be straightforward to be able to pass the row-ID to links in the refresh-email, perhaps even as a pre-fill to another Google Form.

Ideally, it would appear as a standard "Edit" entry in Combined, with a correct new timestamp, echoing down everything from the relevant row, and have a little annotation denoting that it was from the LGTM button.

There may be a clever hack that could let us deploy something quickly; I just can't quite see the implementation yet.

**Comment by awong-dev** [comment]
Here's the first half: https://github.com/findthemasks/findthemasks/pull/956

This generates the links.  Now we just need code that actually does something useful with them.
