### ISSUE TITLE
Add filters menus to v2 embed map

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#862]
On pages where the audience are Makers who use embed versions of the map, the partners who prefer the map-only view needs to have filter categories so they can filter by state/province and particularly PPE items (homemade masks, 3D printed shields etc.)

![image](https://user-images.githubusercontent.com/62862914/81242304-9a651f80-8fc1-11ea-9705-25ce04d4c0af.png)

**proposed solution by devs: make filter menus default, and do not support hide-filter anymore**😃

**Comment by nburt** [comment]
Definitely agree with making filter menus default, that's legacy stuff that should be changed. Any specific reason to remove the hide-filter feature? Why not leave in as a feature?

**Comment by linderr** [comment]
I agree it should remain an option for full modularity. Our narrative with partners/collaborators is something like "this fully functional mini map is going on **your** webpage so please tell us exactly how **you** would like it to be displayed". Current options are:
- list or no list (by default no-list hides filters too)
- map or no map
- perfect default map view with ?coords logic

I am summarizing the suggestion by @saikatbhadra who can better explain himself below 😃

**Comment by linderr** [comment]
Perhaps it is the "inconceivable use case of it/so do we support it" argument?

**Comment by saikatbhadra** [comment]
This is being handled by https://github.com/findthemasks/findthemasks/pull/896

The new behavior is `hide-list` has no effect on `hide-filters`. In the v1 world this feature was linked but now the filters work on any view. We are going to continue to support hide-filters as their are some narrow use cases:
* partner is embedding the map for some specific type of equipment and hence doesn't want users to change the filters
* partner is showing the map on viewports that are narrow and wants to save space on the width
* I'm sure there are other cases I can't think of

The value will default to false so only partners who explicitly ask to hide filters will have filtedr hidden.
