### ISSUE TITLE
Make Contact Card div interactable + center map on pin

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#864]
Matching map view to list was great.
**However, there is no reciprocal way to control the map through the list.**

After entering their hometown or state into the search bar, a user could scroll down the left list and find a listing they like but has no ability to navigate to the exact listing.

**UX/UI dev solution proposed is to make the entire left-hand-side Contact Card div interactable** and ~~linked to a ?coords= based logic first coded by @ngottlieb:~~ do what @ngottlieb suggests below in comments:
![image](https://user-images.githubusercontent.com/62862914/81243383-840c9300-8fc4-11ea-91a9-21848b3bd463.png)

**This would also help with frustrations on mobile** where it is unclear when users tap on the Final Address hyperlink they are going to Google Maps instead of staying on the mobile site #837 Ask 1.
(additional UX/UI mobile v2 designs are in-progress to also address this concern)

Full size dev notes on Figma: https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=183%3A5881

**Comment by nburt** [comment]
We can definitely add a hover state and change the cursor to show that the card is clickable but we'll need a different indicator for mobile since you can't hover

Do we have a way to indicate to users that the card is clickable on mobile?

**Comment by linderr** [comment]
CC @sumitsekhri another mobile v2 feedback to incorporate your original idea.

**Comment by ngottlieb** [comment]
Whoever takes this on (it might be me, but not right now, so commenting for whoever does): I actually would *not* leverage the `coords` action for this. We don't want to link to another page on click, we just want to zoom the map, so the coder of this task should just use the data object to add a click event when the markup is being created that recenters and zooms the map onto the coords.

An alternative, and this may be even better given the abilities it gives us going forward, would be to assign a unique ID to every marker and card (that matches) so we can actually have clicking the card zoom to the marker, not the coords. (In practice, the same, obviously, but framework wise, a bit different and more versatile).

**Comment by nburt** [comment]
Yeah agree with the above - This is possible using the row ID for the US but at a quick glance that doesn't exist for other countries. We could either add it for all countries sheets or we could modify the reloaddatasheet function to add the row id.

**Comment by ngottlieb** [comment]
We could potentially just use a piece of the data (non numeric) as the
unique key, or hash an attribute or something

On May 6, 2020 6:52 PM, "Nathanael Burt" <notifications@github.com> wrote:

Yeah agree with the above - This is possible using the row ID for the US
but at a quick glance that doesn't exist for other countries. We could
either add it for all countries sheets or we could modify the
reloaddatasheet function to add the row id.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/findthemasks/findthemasks/issues/864#issuecomment-624982687>,
or unsubscribe
