### ISSUE TITLE
[embed] Add hover styles to embed page

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#866]
Add hover styles to help indicate that the list embed is clickable and expandable on desktop

**Comment by linderr** [comment]
Done! 👍

**Comment by saikatbhadra** [comment]
Reopening because I don't see any change in the list view when I hover over a listing. It works in the normal site but not on embed. cc @ngottlieb in case there's an easy fix

Clarifying with a user story: "As a user of the embed, I should be see a change in a list view entry  (like a background change to grey) when I hover over an entry to indicate it is clickable"

**Comment by linderr** [comment]
I see a hand hover when I go on the embed collapsed list? PC/Chrome

**Comment by saikatbhadra** [comment]
Oh that's pretty subtle. Guess I was thinking more of a background color change on the whole div rather than just a cursor change. Feel free to close if y'all disagree.

**Comment by ngottlieb** [comment]
No, @saikatbhadra is right, the hover-over-marker-causes-highlight-on-list-view isn't working on embed. I'll check it out

**Comment by ngottlieb** [comment]
that was silly, sorry! fixed.

**Comment by linderr** [comment]
sounds good!

**Comment by linderr** [comment]
and looks good! @ngottlieb Thanks for the suggestion @saikatbhadra
