### ISSUE TITLE
Add country partial for UK About Us page

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#868]
The UK team has grown and is an active part of the FTM community but currently they are on the v1 all-Europe About Us https://findthemasks.com/uk/whoweare

**They should have their own dedicated About Us page using the regional_spotlight.handlebars logic** 

Updated Content for UK team's Regional Spotlight: 
https://docs.google.com/document/d/1b9lj2j3vqJrZgqfozbZ2reSO6xnC_a00VtKO-xxUB7g/edit#bookmark=id.a51x07aweoz

**Comment by zhuochenwang** [comment]
Can the bears interns try to resolve this issue?

**Comment by linderr** [comment]
I could not tag Steph I believe she still has to accept the contributor invite + do 2FA.

**Comment by stephmarisa** [comment]
Hi Linda! Sorry I just set up 2FA and am all ready now!

**Comment by linderr** [comment]
Closed by #1013 !! Good job!!
