### ISSUE TITLE
Expand map view to include all USA states

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#871]
Currently our map view for the US is ignoring:
* Alaska
* Hawaii

Can we add that into the default view (embed and main site)?

**Comment by linderr** [comment]
I'm going to just try to zoom out from 4 (now) to 3 on the locations-list-map.js file. 

@ngottlieb told me before the zoom param, which "allows" decimal, actually works on integer. I had tried it in the early days when he first coded ?coords for the partners to get that perfect default frame for them by doing something crazy like, zoom=11.8 etc. but as soon as you pan on the map, it'll snap to the nearest integer zoom which is kind of jarring UX. 

According to this forum: https://stackoverflow.com/questions/6691979/specific-zoom-in-google-maps  If we want to achieve fancier zoom like doing 3.5  it could be achieved by setting the Gmaps zoom on locations-list-map.js to 3 and adding CSS zoom to 1.5 but apparently we will get a low-resolution result. So maybe it's better to go CSS 0.5 and Gmap zoom 4? 

I don't know how to rig up the CSS properly so please a real dev do that if you want the modularity :) me just go change 4->3

**Comment by linderr** [comment]
Closed by #875
