### ISSUE TITLE
Search bar placeholder text gets obstructed on mobile

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#873]
When the viewport width is very small (like on mobile) the placeholder text "Search by city, zip or address" gets cut off. We should see if we can cut down this text, change its sizing, or do something else to make sure it's still fully visible on all common views.

This bug probably exists in the main page as well

**Comment by linderr** [comment]
“Search by location”? 
![4539B6BB-BBA1-4B08-B74E-73BCB76A231A](https://user-images.githubusercontent.com/62862914/81894798-898a5000-9565-11ea-86b3-8782141d1833.png)
