### ISSUE TITLE
Fix www.findthemakers.com preview text for Facebook / Instagram

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#876]
**Instagram, the preview text for Find the Makers is the Find the Masks text.**
the og:description is already written for /makers and displays fine in other contexts. 

`og:description	
Find the maker groups and spaces that are creating personal protective equipment (PPE) and medical supplies near you`
@notstephen offered "makers is just a cname for masks, so I guess that one was missed."

*edit: just Instagram preview text is at issue:
![image](https://user-images.githubusercontent.com/62862914/81259610-293b6180-8fed-11ea-9b6c-f9929686e495.png)

**Comment by saikatbhadra** [comment]
I believe this is closed as I just tested on Facebook messenger and it is working.

![Screen Shot 2020-05-09 at 8 59 06 AM](https://user-images.githubusercontent.com/2250961/81478599-69f4cf80-91d3-11ea-972f-78c4f38fc6cc.png)

**Comment by linderr** [comment]
I guess fb & Instagram aren’t the same? 
![Uploading B401FDC2-B04B-44D5-8414-FDF59969C8E9.png…]()

**Comment by saikatbhadra** [comment]
Ok so the bug is on www.findthemakers.com not findthemakers.com

## Behavior I want
1. I share www.findthemakers.com on any Facebook property
2. I get the preview text talking about #findthemasks

## Behavior I get
1. I share www.findthemakers.com on any Facebook property
2. I get the preview text talking about #findthemakers

**Comment by linderr** [comment]
?? I think the want & get are opposite? 
The behaviour we want is any mention of (www.)findthemakers.com to show maker preview text 

It currently shows masks preview text ?

**Comment by linderr** [comment]
I tried without www. It’s also:
![5B7C23F3-C363-4002-AED3-0005851733DB](https://user-images.githubusercontent.com/62862914/81479387-bd691c80-91d7-11ea-9364-0df69304090e.png)

**Comment by saikatbhadra** [comment]
Weird - which app are you using?

**Comment by linderr** [comment]
These AM screenshots are Instagram
I just tried FB messenger and it doesn’t work for me either lol. Fb: 
![60B47392-D2CC-4124-8AE3-62EC22758A7C](https://user-images.githubusercontent.com/62862914/81479529-a2e37300-91d8-11ea-931f-4f39387a5381.png)

**Comment by linderr** [comment]
Going to try a different device

**Comment by saikatbhadra** [comment]
Hopefully closed by: https://github.com/findthemasks/findthemasks/pull/895
