### ISSUE TITLE
Update Group Type categories + display new field on Maker form

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#883]
NoM has agreed to allow manufacturers! To accommodate this there are two changes on the form that need to be reflected:

1. They have have added “Manufacturer” option in the Group Type category, which should now be public. 
2. They have added a new field with Minimum Request amounts to facilitate self-matching with smaller makers and manufacturers

**Comment by ngottlieb** [comment]
@linderr as far as I can tell this work has already been done...

**Comment by linderr** [comment]
Ah yes, @awong-dev did it in the same night. We forgot to close, thank you
