### ISSUE TITLE
Add i18n tags to About Us team positions

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#885]
Our names can be English but the positions and team titles should be translated at least. Right now all display in English-only.

**Comment by ngottlieb** [comment]
@linderr can we normalize the titles across countries so they can all use the same i18n strings? i.e. "Lead" vs. "Organizational Lead", "Tech" vs. "Tech Lead", etc.

**Comment by linderr** [comment]
Definitely. Sounds good @ngottlieb !
