### ISSUE TITLE
Make Smarty Streets updates periodic

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#891]
At the moment, the Smarty Streets imports into Combined are manual (last copy was 4/27). We could make them automatic. 

This only affects 4% of our dataset at the moment, but it is the newest 4%.

**Comment by nburt** [comment]
Do you mean beyond hitting `/smarty_streets_analysis/us`? That will run it on anything that has been approved. It is manual and we still could add a trigger for it to run every X minutes.

**Comment by 4kbt** [comment]
Ooo. I didn't know about the URL.

Yeah, triggering that to run as often as the geocoder runs sounds perfect!

**Comment by linderr** [comment]
Hihi has this been done or are we okay with just hitting it manually in our data mod workflow for a while til we have more wizard time? There were some big asks this week :)

**Comment by nburt** [comment]
@4kbt set this up to run every 10 minutes, lmk if there are any issues

**Comment by 4kbt** [comment]
Looks like it is working great! Thank you!
