### ISSUE TITLE
Make data-blog/news link somehow accessible via a pathway from the front page

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#893]
At present, I believe that there is no pathway of any kind to discover https://findthemasks.com/blog/2020-04-21-Data-Insights from the front page.  We can begin to make that article/press-release flow more public.

**Comment by linderr** [comment]
@awong-dev so you are doing this tonight? If so I will leave in M3 :)

**Comment by linderr** [comment]
Closed by #927 😄
