### ISSUE TITLE
Implement v3 filter system design to allow for more filters

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#921]
**We are outgrowing our current 2-menu filter system.**
- #844 request for filtering by entry date, now surfaced by #843 
- #855 makers map needs filters but dataset contains more complicated categories and enums

**@tinabeans has designed a v3 filter system to allow moar filters & more options:**
![image](https://user-images.githubusercontent.com/62862914/81777968-cb07f600-94a6-11ea-9d82-cc84869e3c78.png)
- we may not need the dedicated State/Province filter menu since the search bar can be used for this also; dev's choice
- @4kbt's request for filtering by entry date #844 can be resolved by this UI/UX upgrade and allow a very necessary time-based filter to sort by old/new entries 

Dev Ready design on Figma: https://www.figma.com/file/qbibGHgcV1LBcpvd2EoHSM/FindTheMasks?node-id=924%3A7715

**Comment by nburt** [comment]
Closed by https://github.com/findthemasks/findthemasks/pull/960
