### ISSUE TITLE
Update Media Partner list

### ISSUE THREAD

**Issue by DrewHuntdh** [findthemasks/findthemasks#934]
Hi team,

Can someone please update the media partners page (https://findthemakers.com/uk/makers/partners?locale=en), to include the new UK media outlets found here: https://docs.google.com/spreadsheets/d/1RSiLk3W0GF2V0ATZcSXRVt6kettx9UWbDMCHVwV5xgY/edit?ts=5ea98a96#gid=0 **(Rows 3,4,5)**. The logos can also be found here: https://drive.google.com/drive/folders/1n6rgpTspZSCwlh9uMCQ8wPVDFYvdz0_I in the subfolder: Partner Logos -> Region: EU ->Media Logos.

Slack me if you need more info. Thanks

**Comment by linderr** [comment]
Added 2/3 they were all the same story so I chose two entities and omitted Professional Heating & Plumbing and went for the two most distinct logos #950
