### ISSUE TITLE
New updates are not appearing in the map.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#951]
Hi!   Looks like Drew has found a bug. 

reloadsheetdata's output changed a few days ago to something with more structure than html.   He was curious about it, so I looked into whether or not recent edits had been applied to the map. They have not.

Ctrl+F searching for "Butterfly" within the reloadsheetdata output shows that entry 5359 was properly updated on 5/19/2020 . "The Butterfly Effect Project"'s entry in the map still shows a date of April 26, 2020.

Similarly, a new entry for Neurolutions, with zip code 63110 appears in the reloadsheetdata output, but not in the map.

**Comment by DrewHuntdh** [comment]
Example of an edit that hasn't taken effect. I removed this listing from the sheet, it has updated it in the data reload, but still showing on the website. 

![image](https://user-images.githubusercontent.com/64538168/82476468-0a959a00-9ac6-11ea-8021-ed15ccc15feb.png)

**Comment by nburt** [comment]
I think that Albert fixed this earlier today, closing
