### ISSUE TITLE
Layer System Legend

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#959]
Increasing number of groups have various datasets (needs, makers, testing centres, case number, risk number, open/shelter-in-place policy status) who want to partner via a data "overlay/layer" system. Users shouldn't have to go to 6 websites for 6 datasets.

**Let's try this logic by just layering on our own Find the Maker data set onto the Find the Masks map, and vice versa.**

@awong-dev suggests: 
- on the Masks map, PPE needs should stay the primary dataset while the Makers is the secondary dataset
- on the Makers map, makers stay the primary dataset while PPE needs is the secondary dataset

Other notes:
- the X of Y counter should not include all datasets (only counts primary dataset Requests v. Groups)
- @ngottlieb thinks secondary datasets do not appear in left-hand list view
- @ngottlieb thinks secondary datasets only appear in map-view and you can click on them to trigger the pop-up info card
- clustering of second dataset should be uniformly one color #d9d9d9 grey
- upon zooming in, single pin resolution will show the following below

@sumitsekhri has suggested to keep the pin outline but use different iconography within the pin.
![image](https://user-images.githubusercontent.com/62862914/82782578-7bfc8200-9e11-11ea-9c68-4189131b9e3a.png)

Makers dataset using **gear icon** in pin. Resources: 
- https://materialdesignicons.com/icon/cog
- https://materialdesignicons.com/icon/cog-outline
- Correct yellow should be Find the Makers yellow #FDC276 (not pictured above)

Reference: sister FTM-FR site shows both needs and makers on one map.
![image](https://user-images.githubusercontent.com/62862914/82783343-1ad5ae00-9e13-11ea-8a86-9bdacd71de5f.png)
https://protegeons-nos-soignants.fr/carte-globale/

**Comment by nburt** [comment]
@linderr a few questions:

1. Do we have the icon with the gear in it yet? What should the "hover" color be for makers? Do we assume that each dataset will have its own icon? (requester = regular, maker = gear, etc.)
2. Sounds like primary and secondary datasets should be clustered separately? Are they clustered as primary vs. secondary or is each dataset clustered separately?
3. @ngottlieb curious about the list-view. Why do you think secondary datasets should be excluded from that? Would it be confusing if you added a new dataset and the X of Y numbers don't change while the map does?
4. How do users add secondary datasets? Is there a multi select dropdown in the filters? Is it toggleable from a legend over the map? If a filter I think this is probably a pre req - https://github.com/findthemasks/findthemasks/issues/921

**Comment by ngottlieb** [comment]
@nburt yeah, I think that's the confusion I was imagining we could avoid. If filters and the requester count are only applying to our primary dataset, having the secondary data displayed in the list view but not reflected in those two controls seems confusing. I imagine it more like if you're using a map and you turn on "topo lines" or "roads" or some other map layer -- it adds to the picture, but your main dataset is still the focus. I'm open to other approaches though.

**Comment by linderr** [comment]
@nburt 
1. Hover colour you pick - green? #3CB371
Icon file - not yet. What file type do you prefer? .svg/.png? I don't think I can get an UX/UI person on this in a timely manner but will attempt to do it myself today =]
each dataset having its own icon --- yes, sir

2. Clustering - Primary vs. Secondary sounds good but whatever is easiest and/or makes more sense on the coding side? It makes sense to me that all secondary layers are clustered but that sounds hard? Please engage a #dev talk :) I think you're making good UX/dev trade offs so it could also work that primary clusters (normal, coloured) and each secondary is clustered in grey if that's easiest!!


4. (fluid consciousness) I agree with Nick that the primary focus should be main dataset on each respective map. My understanding from @awong-dev & @ngottlieb that other options are different icons or perhaps adopt the dimming logic. 
Filtering secondary datasets sounds like an great iteration - do you guys think it's necessary for a first pass?
@nburt your legend idea sounds good especially if we are getting rid of the canonical satellite/terrain toggles we can use that space to do our own legend instead. Ultimately whether this legend is toggle-able on first pass is up to you guys --- I think we if we don't do the secondary-filters then non-toggleable legend is fine (assuming same logic) 
more thoughts: Our layers will be heavier on Needs vs. individual other datasets. On the Needs map I think a static/non-toggleable legend is fine but on say, the Maker map it does makes sense be focus on Makers above anything else. Is this where we can re-adopt dimming? @awong-dev previously suggested using dimming on secondary datasets similar to how do we do other countries

**Comment by nburt** [comment]
1) svg is probably best, then jpg, then png but as long as the file size is small it'll be fine
2) OK - let's just go with primary clusters being normal and all secondary clusters as gray (this could be 1 to N depending on how many we end up adding)
3) I guess for this it sorta depends on where the control to add in these secondary datasets lives. If it's in the filters, I think that they should also go into the list view. If it's a legend of sorts on the map I think it can just apply there. My one concern there is that if we're really trying to apply multiple secondary datasets (makers, getusppe affiliates, testing locations, etc.) the legend probably needs to become a multi select dropdown filter and would take up too much space over the map (especially on mobile). 

I'm not sure I'm understanding the use case for dimming here. If someone is choosing to add on an additional dataset wouldn't they want it to be clear?

**Comment by linderr** [comment]
1. Soooo I tried to bootleg a copy of Illustrator and realized 😄 I don't know how to vectorize anything haha. Got Sumit to do a vector version of the final pin tonight. If not, I will watch a YouTube later to figure it out. 
2. Sounds great!
3. I agree with you that dimming may be confusing --- because if we don't want the secondary datasets to be seen then why bother? I'm personally a visual person so perhaps we need to see everything full-brightness to see if it's too crazy or fine. 

Some maps use the a pin icons themselves as legend to mult-select layers. Example:
https://www.damerousky.cz/places?lat=50.075816882516534&lng=14.459381103515627&zoom=9

**Comment by linderr** [comment]
@nburt @sumitsekhri came through:
We need to test if we need to up the size of the gears. This is .png for now but he'll merge as .svg later

<img width="124" alt="Frame 1" src="https://user-images.githubusercontent.com/62862914/82848752-bdd90700-9ea9-11ea-9fd3-7698b3ddc69c.png">

**Comment by nburt** [comment]
Do you have a transparent version of it?

I can resize the image myself but the background is white
![image](https://user-images.githubusercontent.com/5788989/82850167-3bf8d600-9ec9-11ea-8021-57d4b2874eb8.png)

Our current markers are 22 x 40. I think that if we're going to update the UX for makers (I like this marker a lot!) maybe we should align the markers with the requester map too?

I'm thinking that for requesters we have a red + darker red (hover) and then for makers it's orange + darker orange (hover). The requesters one could look like the one above but just be fully filled in.

@linderr do you have an opinion on what to use for the getusppe affiliates dataset? Should it just be the same as the requester one for now?

@sumitsekhri is it possible to get images for all of those? Since our main markers now are skinnier than above I think it might look a bit weird

**Comment by linderr** [comment]
@nburt asking for transparent one to be sent to #dev and @ you :)

For GUP, I've asked for their shield logo today --- if that's too busy (due to tiny mask details) we can use a four-pointed shield in their org colours. https://materialdesignicons.com/icon/shield

**Comment by linderr** [comment]
@nburt GUP we can use this and see if it's too crazy:
![LogoOnly](https://user-images.githubusercontent.com/62862914/82858646-5468f080-9ec9-11ea-8451-4872610c74d3.png)

**Comment by nburt** [comment]
Closed by https://github.com/findthemasks/findthemasks/pull/969
