### ISSUE TITLE
Add formal license to downloadable data

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#967]
As we've gotten a request to formalize our data licensing, ftm-makers and US-data have tentatively settled on licensing using the Open Database License

https://opendatacommons.org/licenses/odbl/index.html

Let's find a low-impact way to add a reference to the license to our data.json and data.csv outputs.

**Comment by linderr** [comment]
Yay we finally did it! Closed by #1010 but it's CC4-SA :)
