### ISSUE TITLE
Understand instaqueries

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#972]
Almost every time we send out MailChimp emails, we get a few "insta-queries" that hit malformed versions of the mapline URL.  These queries hit our Analytics within seconds of the MailChimp send, so they are surely automated. Can we understand these links better to make sure we're not doing something wrong?

Oodles of examples are archived in the launch threads in #data-refresh-email

**Comment by linderr** [comment]
A deep dive into the MC universe :)

**Comment by 4kbt** [comment]
I believe that the easy-button reformation of the emails has sidestepped this problem. Closing for now, but for the truly curious, it'd be fun to understand.
