### ISSUE TITLE
Scale responses to contact@

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#98]
Right now, contact@findthemasks.com is set up as a dreamhost fwd only email address pointing at my personal email. I would like to figure out better handling for email as traffic grows.

I've observed these types of incoming email:
1. Data additions, updates, and takedowns. These should go to the data moderation team. If they could end up posted in the "#data" slack, then people could say they're on it and when they're done. And hopefully trigger a reply back to let the person know - but that's not p0. It would be equivalent to automatically reply "Thank you, we'll get this up ASAP!" on receipt. (note: right now I often ask people emailing to submit the form themselves, but I also have a lot of new volunteers chomping at the bit for tasks, and form entry would be a great fit for new folks)
2. Offers to sell us masks, or questions about retooling a factory to make masks. This is awesome to see but our project isn't set up to handle it. I forward these to our friends at maskup2020@gmail.com (https://pg.gl) who are able to consider and fund shipments of masks.
3. Offers to collaborate, which core contributors should continue to handle manually (eg could scale from just me to me and a few others, but can't be a ruleset)
4. Press inquiries. Not many so far but could be more in coming days.

Ideas on what to improve here?

**Comment by eZanmoto** [comment]
Emails could be sent to Slack, but it requires a paid Slack plan (https://slack.com/intl/en-ie/slack-tips/send-email-to-slack). In a nutshell, you'll add the Email App (https://slack.com/apps/A0F81496D-email) to Slack and it'll generate an email address for a channel, which you can set up as a forwarding email for contact@findthemasks.com. You could create a channel and email per "topic" to automatically categorise messages (e.g. data@findthemasks.com, press@findthemasks.com, etc.) Just some ideas.

**Comment by cchang-adi** [comment]
On the pricing page, Free users get "10 integrations with other apps like Google Drive, Office 365 and many more" (https://slack.com/pricing), so maybe we don't need a paid plan to use this? Not sure.

In the meantime, maybe create a data-only gmail to forward requests to, and give access to that account to the data team? We could even post a fwd-only data update email to the site that people can send requests to directly, to minimize forwarding by hand.

**Comment by eZanmoto** [comment]
I actually tried adding it to test it out, but it said "This integration is only available to workspaces on paid plans."

**Comment by cchang-adi** [comment]
Ok, I think posting a forwarding address to a data-only email might be the right way to go then.
